### PR TITLE
fix(install): Don't show manifest while updating

### PR DESCRIPTION
**Pull request by niheaven**
Don't show manifest while 'scoop update` (https://github.com/ScoopInstaller/Scoop/pull/4155#issuecomment-993554265)

### CODE REVIEW

**Comment by rashil2000** [comment]
I already updated all my apps 😅 How to test this?

**Comment by niheaven** [comment]
Wait until next day? 🤣

**Comment by niheaven** [comment]
@rashil2000 Tested?

**Review by rashil2000 — APPROVED** [review]
Yes

**Pull request merged**
