### PR TITLE
fix(versions): Get current version from failed installation if possible

### LINKED ISSUE #4573: Reinstate 'current' junctions as a part of `scoop reset`
## Bug Report

**Package Name:** [name of package which has bug(s)]
scoop 

### Current Behaviour
Scoop uses a NTFS-directory-junction 'current` to point to the active-version of an app.
The NTFS junction is absolute.
Hence when scoop is ```xcopy```-ed into a VHDX and remounted on another windows-OS installation, the scoop root folder may not be in exactly the same location. (```xcopy /H /E /B /O /K /Y src dst```)
As a result powershell-function ```app_status()``` is not able to descend into the junction to retrieve the installed manifest,json and hence scoop list throws an error .

```
PS C:\vol\scoop_01\scoop\apps\scoop\current\lib> scoop list
Installed apps:

  7zip 21.06 *global* [main]
  adb  *global* *failed*
  android-sdk  *global* *failed*
  anki  *global* *failed*
  blender  *global* *failed*
  colortool  *global* *failed*
  doublecmd  *global* *failed*
```

The NTFS-directory-junction contains path from the other operating system, which is invalid on the new one.
Hence, errors.

### Expected Behaviour
Scoop should still work when copied for portability sake, instead of requiring user to install applications afresh

Perhaps instead of NTFS-junction, consider using 
- symbolic link ```mklink /d current 21.06```
Junction-links are always absolute, when copied point to the original mount path, environment variables cannot be embedded.

I want scoop to be
- located on a VHDX/partition etc,
- be mounted anywhere by any of a multi-boot multi-windows operating systems.

### Workaround
- mount the VHDX/partition in exactly same path on each windows operating system such as ```C:\vol\scoop_01\scoop ```
- include a small script to fix the junctions, in a manner similar to ```scoop reset```

### Possible Solution
- use symbolic links? 

### System details

**Windows version:** [e.g. 7, 8, 10]
Windows-10 and Windows-11

**OS architecture:** [e.g. 32bit, 64bit]
64-bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
PS C:\Users\admin> echo $PSVersionTable

Name                           Value
PSVersion                      5.1.22000.282
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.282
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Additional software:** [(optional) e.g. ConEmu, Git]

### LINKED ISSUE #4684: no help of ``scoop reset *``
After reinstalling the system, i do as [#2894](https://github.com/ScoopInstaller/Scoop/issues/2894), i copy ``scoop`` to ``c:\user\x\``, and i add the ``Path`` and ``SCOOP``

but when i run ``scoop reset *``,i got
```
PS C:\Users\zuokan> scoop reset *
ERROR '7zip ()' isn't installed
ERROR 'clash ()' isn't installed
ERROR 'git ()' isn't installed
ERROR 'neteasemusic ()' isn't installed
ERROR 'steam ()' isn't installed
ERROR 'vscode ()' isn't installed
```
run ``scoop list``,got this
```
PS C:\Users\zuokan> scoop list
Installed apps:
  7zip  *failed*
  clash  *failed*
  git  *failed*
  neteasemusic  *failed*
  steam  *failed*
  vscode  *failed*
```
``SCOOP``: ``C:\User\zuokan\scoop``

**Windows version:** 10

**OS architecture:** 64

**PowerShell version:** Major 5 ,Minor 1 ,Build 22000 ,Revision 282

```json
{
    "lastupdate":  "2022-01-23T23:51:51.1889212+08:00",
    "SCOOP_REPO":  "https://gitee.com/glsnames/Scoop-Core",
    "SCOOP_BRANCH":  "master"
}
```

### PR DESCRIPTION
**Pull request by niheaven**
#### Description

This PR changes some UX after https://github.com/ScoopInstaller/Scoop/pull/3721, which cause `scoop reset <app>` not works as before (some use cases that I missed)

- `lib\versions.ps1`: `Select-CurrentVersion()` now get version from `current` folder or latest installed version
- `lib\install.ps1`: `ensure_none_failed()` just reset failed app if it is installed successfully before
- `lib\core.ps1`: `failed()` could figure out failed installation with new `Select-CurrentVersion()` function
- `libexec\scoop-list.ps1`: Correctly mark failed app
- `libexec\scoop-install.ps1`: Use `ensure_none_failed()` before installing apps
- `libexec\scoop-update.ps1`: Use `ensure_none_failed()` before updating apps

#### Motivation and Context

- Fixes #4573
- Fixes #4684

- Relates to https://github.com/ScoopInstaller/Scoop/issues/4508#issuecomment-1015075463

#### How Has This Been Tested?

Remove `current` junction in `7zip`

Before:

```pwsh
❯ Get-ChildItem D:\Scoop\apps\7zip

    Directory: D:\Scoop\apps\7zip

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----            2022/2/8     1:01                21.07

❯ scoop list 7zip
Installed apps matching '7zip':

  7zip  *failed*
  7zip-zstd v21.03-v1.5.0-R2 [versions]

❯ scoop reset 7zip
ERROR '7zip' isn't installed

❯ scoop uninstall 7zip
ERROR '7zip' isn't installed correctly.
Removing older version (21.07).
'7zip' was uninstalled.
```

After:

```pwsh
❯ Get-ChildItem D:\Scoop\apps\7zip

    Directory: D:\Scoop\apps\7zip

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d----            2022/2/8     1:43                21.07

❯ scoop list 7zip
Installed apps matching '7zip':

  7zip 21.07 *failed* [main]
  7zip-zstd v21.03-v1.5.0-R2 [versions]

❯ scoop reset 7zip
Resetting 7zip (21.07).
Linking D:\Scoop\apps\7zip\current => D:\Scoop\apps\7zip\21.07
Creating shim for '7z'.
Creating shortcut for 7-Zip (7zFM.exe)
Persisting Codecs
Persisting Formats

# Remove `current` junction again
❯ scoop install 7zip
WARN  Repair previous failed installation of 7zip.
Resetting 7zip (21.07).
Linking D:\Scoop\apps\7zip\current => D:\Scoop\apps\7zip\21.07
Creating shim for '7z'.
Creating shortcut for 7-Zip (7zFM.exe)
Persisting Codecs
Persisting Formats
WARN  '7zip' (21.07) is already installed.
Use 'scoop update 7zip' to install a new version.

# Now remove `current` junction in `7zip` and all content under `7zip-zstd`
❯ scoop list 7zip
Installed apps matching '7zip':

  7zip 21.07 *failed* [main]
  7zip-zstd  *failed*

❯ scoop update 7zip-zstd
ERROR '7zip-zstd' isn't installed correctly.
INFO  Please reinstall it or fix the manifest.
Latest versions for all apps are installed! For more information try 'scoop status'

❯ scoop install 7zip-zstd
WARN  Purging previous failed installation of 7zip-zstd.
ERROR '7zip-zstd' isn't installed correctly.
'7zip-zstd' was uninstalled.
WARN  Repair previous failed installation of 7zip.
Resetting 7zip (21.07).
Linking D:\Scoop\apps\7zip\current => D:\Scoop\apps\7zip\21.07
Creating shim for '7z'.
WARN  Overwriting shim ('7z.exe' -> '7z.exe') installed from 7zip-zstd
Creating shortcut for 7-Zip (7zFM.exe)
Persisting Codecs
Persisting Formats
Installing '7zip-zstd' (v21.03-v1.5.0-R2) [64bit]
Loading 7z21.03-zstd-x64.exe from cache.
Checking hash of 7z21.03-zstd-x64.exe ... ok.
Extracting dl.7z ... done.
Linking D:\Scoop\apps\7zip-zstd\current => D:\Scoop\apps\7zip-zstd\v21.03-v1.5.0-R2
Creating shim for '7z'.
WARN  Overwriting shim ('7z.exe' -> '7z.exe') installed from 7zip
Creating shim for '7zG'.
Creating shortcut for 7-Zip (7zFM.exe)
'7zip-zstd' (v21.03-v1.5.0-R2) was installed successfully!
```

#### Checklist:

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
- [x] I have updated the documentation accordingly.
- [x] ~I have updated the tests accordingly.~

### CODE REVIEW

**Comment by rashil2000** [comment]
I think this also solves https://github.com/ScoopInstaller/Scoop/issues/4573

**Comment by rashil2000** [comment]
And maybe https://github.com/ScoopInstaller/Scoop/issues/4474 and https://github.com/ScoopInstaller/Scoop/issues/4350 too?

**Comment by niheaven** [comment]
> This also solves #4573

#4573 is fixed here, but #4474 and #4350 need some other changes.

**Comment by niheaven** [comment]
#4722 fixes #4350 and #4474

**Pull request merged**
