### PR TITLE
Avoid shim blocking when running a GUI app 

### PR DESCRIPTION
**Pull request by milnak**
#### Description
Currently scoop shim will block when running a GUI app.  

To repro this, do the following from a  powershell console:

```PowerShell
scoop install extras/notepad2-zufuliu
notepad2
```

The console will be blocked until notepad exits.

I have added an environment variable that can be set to override this behavior.

#### Motivation and Context
Relates to #1606 

#### How Has This Been Tested?
Build shim, verified against notepad2 and console apps.

#### Checklist:
- [X] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
- [X] I have ensured that I am targeting the `develop` branch.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.
- [ ] I have added an entry in the CHANGELOG.

### CODE REVIEW

**Comment by milnak** [comment]
looks like visual studio did some reformatting of the file. If you want me to undo those reformats, let me know and ill  push a new iter.

**Comment by spider2048** [comment]
Using the develop branch (which had #5559 and #5684 merged recently) would solve the issue for every shim type.
So, this is implemented in the develop branch.

But, when a target application uses `AttachConsole` to obtain console handles, both the current develop branch and your's won't be able to. For instance,
```
$ scoop config shim scoopcs
$ scoop install alacritty
$ alacritty -h
<blank>
```

There is #5721 waiting for approval which would solve this issue.
Because of [this](https://github.com/ScoopInstaller/Scoop/blob/8c4988e1a36e592529ce3f355b7950bdd8e2c471/supporting/shimexe/shim.cs#L139C1-L150C10), the process can't obtain the handles to console just by using `AttachConsole`, because the shim exits.

**Comment by milnak** [comment]
@spider2048 it looks like your changes handle this case and more, so this PR can likely be closed.

**Comment by amorphobia** [comment]
Since the fix is not released yet (will be in 0.4.0), I provide a workaround for current version (0.3.1).

Save following as `np2.ps1` in your `$env:Path`:
```PowerShell
if ($args.Length -lt 1) {
    Start-Process -WindowStyle hidden notepad2.exe
} else {
    Start-Process -WindowStyle hidden notepad2.exe ($args -join ' ')
}
```

Just use `np2 [file_path]` from command line.

**Pull request closed without merging**
