### PR TITLE
Fix #4000, handle arch-specific env_add_path

### LINKED ISSUE #4000: Scoop-Reset: The architecture specific 'env_add_path' would not be reset.
Hi, all.

Recently, I've tried to move my `SCOOP` home to another directory, and I can not reset the architecture specific `env_add_path` stated in some of my custom manifests. For example, I have a snippet of the manifest looks like this:
```
{
    //...
    "architecture": {
        "64bit": {
            "env_add_path": [
                "Bin",
                "Tools"
            ]
        },
        "32bit": {
            "env_add_path": [
                "Bin32",
                "Tools32"
            ]
        }
    },
    //...
}
```

It is expected that the path should be set targeting my new `SCOOP_HOME`, yet it did not.

After some debugging, I found out that the function `env_add_path` *https://github.com/lukesampson/scoop/blob/96de9c14bb483f9278e4b0a9e22b1923ee752901/lib/install.ps1#L940* actually takes an `$arch` parameter, yet the calling line of `env_add_path $manifest $dir` *https://github.com/lukesampson/scoop/blob/96de9c14bb483f9278e4b0a9e22b1923ee752901/libexec/scoop-reset.ps1#L76* choose not to pass the `$architecture` as well as the `$global`.

**So...** 
Is this line intended to be like this and why, or just an inadvertent issue and I should submit a PR?

### PR DESCRIPTION
**Pull request by sinloss**
This fixes #4000

### CODE REVIEW

**Comment by sinloss** [comment]
> * Fix `env_set` (env_rm) too 
> ...
> 
> In this codebase it has to be fixed on multiple places.
> 
> * bin\uninstall
> * libexec\scoop-update
> * libexec\scoop-uninstall
> 
> [Ash258@81ad387](https://github.com/Ash258/Scoop-Core/commit/81ad387c9e61d867f61083df945ab3bd83dad125)

Sure, I'll see to it.

**Comment by sinloss** [comment]
@Ash258 And you are working on the `Pester 5.0` issue! That's great!

**Comment by Ash258** [comment]
My changes will not go here.

**Comment by sinloss** [comment]
> My changes will not go here.

Mind me asking why?

**Review by rashil2000 — APPROVED** [review]

**Comment by niheaven** [comment]
@rashil2000 You should merge everything into `develop` and test it, then merge `develop` into `master`.

**Comment by rashil2000** [comment]
Will keep that in mind. What about PR's that already have `master` as their target branch?

**Comment by niheaven** [comment]
Retarget them, by using `Edit` button near title.

**Comment by rashil2000** [comment]
Sure, thanks!

**Pull request merged**
