### PR TITLE
fix(search_bucket): set default and check type before using

### PR DESCRIPTION
**Pull request by Orion-zhen**
#### Description

1. check type of `RootElement` before calling `TryGetProperty`
2. if `RootElement` is an array, do not try to get `version`, use default value instead

Changes above should avoid calling `TryGetProperty` when `RootElement` is an array.

#### Motivation and Context

Closes [#issue6149](https://github.com/ScoopInstaller/Scoop/issues/6149)

#### How Has This Been Tested?

I ran my simple test in:

- Windows version: 11
- OS architecture: 64bit
- PowerShell version: 7.4.5

Without my commit, the `scoop search` shows this:

image

> note: the error message will be shown for multiple times, I sent siginit to powershell to avoid too many messages

With my commit, the `scoop search` shows this:

image

> no error messages are shown

Displayed in one picture:

image

#### Checklist:

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
- [x] I have ensured that I am targeting the `develop` branch.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.
- [ ] I have added an entry in the CHANGELOG.

### CODE REVIEW

**Comment by xrgzs** [comment]
I have the same issue. It only happens in PowerShell 7. Hope to merge these codes as soon as possible.

**Comment by Super1Windcloud** [comment]
@r15ch13   @niheaven  @deevus  @lukesampson

**Comment by niheaven** [comment]
Couldn't reproduce, it's strange.

**Comment by Orion-zhen** [comment]
The error only occurs in powershell version 7.x

**Comment by xrgzs** [comment]
> Couldn't reproduce, it's strange.

add this bucket, 100% reproduce: https://github.com/kkzzhizhou/scoop-apps

**Comment by niheaven** [comment]
> > Couldn't reproduce, it's strange.
> 
> add this bucket, 100% reproduce: [kkzzhizhou/scoop-apps](https://github.com/kkzzhizhou/scoop-apps)

The bucket is unofficial and not well-maintained, containing a non-manifest in the bucket subdirectory (such as `custom-snippets.json`, which causes this bug, and a 0-byte `FFmpegBatchAVConverter.json`).

Please submit a PR to the bucket's repository to address the bug.

**Comment by kkzzhizhou** [comment]
> > > Couldn't reproduce, it's strange.
> > 
> > 
> > add this bucket, 100% reproduce: [kkzzhizhou/scoop-apps](https://github.com/kkzzhizhou/scoop-apps)
> 
> The bucket is unofficial and not well-maintained, containing a non-manifest in the bucket subdirectory (such as `custom-snippets.json`, which causes this bug, and a 0-byte `FFmpegBatchAVConverter.json`).
> 
> Please submit a PR to the bucket's repository to address the bug.

fix

**Pull request closed without merging**
