### PR TITLE
chore(release): Bump to version 0.1.0

### PR DESCRIPTION
**Pull request by niheaven**
### Features

- **scoop-bucket:** List more detailed information for buckets (#4704, #4756, #4759)
- **scoop-cache:** Handle multiple apps and show detailed information (#4738)
- **scoop-cat:** Use `bat` to pretty-print JSON (#4742)
- **scoop-config:** Allow Scoop to ignore running processes during reset/uninstall/update (#4713, #4731)
- **scoop-config:** Show all settings (#4765)
- **scoop-download:** Add `scoop download` command (#4621)
- **scoop-(install|virustotal):** Allow skipping update check (#4634)
- **scoop-list:** Allow list manipulation (#4718)
- **scoop-list:** Show last-updated time (#4723)
- **scoop-info:** Revamp details and show more information (#4747)
- **scoop-shim:** Add `scoop shim` to manipulate shims (#4727, #4736)

### Bug Fixes

- **autoupdate:** Allow checksum file that contains whitespaces (#4619)
- **autoupdate:** Rename $response to $res (#4706)
- **config:** Ensure manipulating config with UTF8 encoding (#4644)
- **config:** Allow scoop config use Unicode characters (#4631)
- **config:** Fix `set_config` bugs (#3681)
- **current:** Remove 'current' while it's not a junction (#4687)
- **depends:** Prevent error on no URL (#4595)
- **depends:** Check if extractor is available (#4042)
- **decompress:** Fix nested Zstd archive extraction (#4608, #4639)
- **installed:** Fix 'core/installed' that mark failed app as 'installed' (#4650, #4676, #4689)
- **no-junctions:** Fix error when `NO_JUNCTIONS` is been set (#4722, #4726)
- **shim:** Fix PS1 shim error when in different drive in PS7 (#4614)
- **shim:** Fix `sh` shim error in WSL (#4637)
- **shim:** Use `-file` instead of `-command` in ps1 script shims (#4721)
- **shim:** Fix exe shim when app path has white spaces (#4734, #4780)
- **versions:** Fix wrong version number when only one version dir (#4679)
- **versions:** Get current version from failed installation if possible (#4720, #4725)
- **scoop-alias:** Fix alias initialization (#4737)
- **scoop-checkup:** Skip 'check_windows_defender' when have not admin privileges (#4699)
- **scoop-cleanup:** Remove apps other than current version (#4665)
- **scoop-search:** Remove redundant 'bucket/' in search result (#4773)
- **scoop-update:** Skip updating non git buckets (#4670, #4672)

### Performance Improvements

- **uninstall:** Avoid checking all files for unlinking persisted data (#4681, #4763)

### Code Refactoring

- **depends:** Rewrite 'depends.ps1' (#4638, #4673)
- **mklink:** Use 'New-Item' instead of 'mklink' (#4690)
- **rmdir:** Use 'Remove-Item' instead of 'rmdir' (#4691)
- **COMSPEC:** Deprecate use of subshell cmd.exe (#4692)
- **git:** Use 'git -C' to specify the work directory instead of 'Push-Location'/'Pop-Location' (#4697)
- **scoop-info:** Use List View for output (#4741)
- **scoop-config:** Use underscores everywhere (#4745)

### Builds

- **checkver:** Fix output with '-Version' (#3774)
- **schema:** Add '$schema' property (#4623)
- **schema:** Add explicit escape to opening bracket matcher in jp/jsonpath regex (#3719)
- **schema:** Fix typo ('note' -> 'notes') (#4678)
- **tests:** Support both AppVeyor and GitHub Actions (#4655)
- **tests:** Run GitHub Actions CI on each commit (#4664)
- **tests:** Use cache in GitHub Actions (#4671)
- **tests:** Disable CI test on 'push' (#4677)
- **vscode-settings:** Remove 'formatOnSave' trigger (#4635)

### Styles

- **test:** Format scripts by VSCode's PowerShell extension (#4609)
- **style:** Use correct casing for `$PSScriptRoot` (#4775)

### Tests

- **test-bin:** Only write output file in CI and fix trailing whitespaces (#4613)
- **manifest:** Fix manifests validation (#4620)
- **zstd:** Fix 'zstd' extraction error in test (#4651)

### Documentation

- **changelog:** Add 'CHANGLOG.md' (#4600)
- **changelog:** Rearrange CHANGELOG (#4729, #4770, #4774)
- **changelog:** Link CHANGELOG headers to 'releases/tag' (#4730)

Thanks to the following contributors (ordered by PR merging time):

@niheaven @rashil2000 @issaclin32 @caoli5288 @axtens @ParkerM @mgziminsky @ipcjs @chawyehsu @HUMORCE @snowman @jantari @younger-1 @zStruCat

### CODE REVIEW

**Comment by rashil2000** [comment]
I guess from next time we should include the "issue number that is closed" by a PR in the changelog itself. Right now we will have to go to all PRs and close them individually...

**Comment by niheaven** [comment]
Check if the issues are closed when this PR is merged. This may be automatic since the related PRs (that mentioned closing issues) are merged into `master`.

If not, I'll add `Close #xxx` in PR's description next time.

**Comment by rashil2000** [comment]
> Last time I used `Squash and merge` which is not the correct merging method 🤣
> 
> This PR should be merged using merge commit.

`Squash and merge` can close issues (see the various PRs in Main, Extras, for examples), so I think it does not depend on merge strategy.

**Comment by HUMORCE** [comment]
> What is fixes to unreleased features?

e.g.
```
feat:
scoop-bucket: List more detailed information for buckets (https://github.com/ScoopInstaller/Scoop/pull/4704)
fixes:
scoop-bucket: Check for git before running command (https://github.com/ScoopInstaller/Scoop/pull/4756)
scoop-bucket: Fix date formatting issues with git bucket (https://github.com/ScoopInstaller/Scoop/pull/4759)
```

**Comment by niheaven** [comment]
`Squash and merge` could close issues that explicitly mentioned in PR's description, but since the PR is squashed into one, there is no mentioning in its body.

Ref: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#about-linked-issues-and-pull-requests

> When you merge a linked pull request into the default branch of a repository, its linked issue is automatically closed.

**Comment by niheaven** [comment]
@HUMORCE This is added to CHANGELOG within the PR, and #4764 just change `Unreleased` tag to `v0.1.0`. A new `Unreleased` will be added in `develop` branch after this is merged. Do I misunderstand something?

**Comment by HUMORCE** [comment]
i just noticed that you edited CHANGELOG in #4759 currently, so i asked the question here.

the changelog should be relative to the previous version(master branch). #4756 #4759 does not fix anything in the master branch, they fix new feat. by #4704 in develop branch only.

**Comment by niheaven** [comment]
> the changelog should be relative to the previous version(master branch). #4756 #4759 does not fix anything in the master branch, they fix new feat. by #4704 in develop branch only.

Yes, I try to edit these PR as:

> - **scoop-shim:** Add `scoop shim` to manipulate shims ([#4727](https://github.com/ScoopInstaller/Scoop/issues/4727), [#4736](https://github.com/ScoopInstaller/Scoop/issues/4736))

i.e., put them all together. But I only merge PRs familiar, so could you submit a PR to fix these logs? Merge it before this one should be okay.

**Comment by niheaven** [comment]
If develop branch has been fully tested, could you guys @ScoopInstaller/maintainers approve this commit and keep moving on？

**Review by rashil2000 — DISMISSED** [review]
Be careful with the merge strategy this time 😅

**Comment by HUMORCE** [comment]
sccop-which is broken, now

**Comment by rashil2000** [comment]
Oh. Is it because of the double quotes that were added recently to shim files?

**Comment by HUMORCE** [comment]
> Oh. Is it because of the double quotes that were added recently to shim files? 

remove L32-35 at scoop-which, then work properly.

**Comment by niheaven** [comment]
@HUMORCE Fixed in #4780

**Review by rashil2000 — APPROVED** [review]

**Review by HUMORCE — APPROVED** [review]

**Comment by niheaven** [comment]
Damn, it still doesn't close related issues... I'll manually close them and link issues next time 😭

**Comment by rashil2000** [comment]
No issues got closed :(

**Pull request merged**
