### PR TITLE
fix(shim-kiennq): Update shimexe file name

### PR DESCRIPTION
**Pull request by kiennq**
With the new build pipeline in https://github.com/kiennq/scoop-better-shimexe/commit/db29490243810674bfa35c5017fbdc96acede9f9, the artifact name will be `shimexe.zip` only

### CODE REVIEW

**Comment by rashil2000** [comment]
Please use the `develop` branch instead of `master`

**Comment by kiennq** [comment]
> Please use the `develop` branch instead of `master`

Done

**Review by rasa — APPROVED** [review]

**Comment by niheaven** [comment]
Update the CHANGELOG?

**Comment by kiennq** [comment]
@niheaven I don't think this update is needed a CHANGELOG.
And for the purpose of this Makefile, I assume that @rasa is using it to automatically update to the latest release version of the shimexe

**Comment by rasa** [comment]
> I assume that @rasa is using it to automatically update to the latest release version of the shimexe

 It's run manually, though it could be called by a GitHub Action.

**Comment by niheaven** [comment]
> @niheaven I don't think this update is needed a CHANGELOG. And for the purpose of this Makefile, I assume that @rasa is using it to automatically update to the latest release version of the shimexe

Yes, I agree, so I'm asking why there's a Makefile 😄 

I'll merge it and let's think about the future way of update the shim.

**Pull request merged**
