### PR TITLE
fix(core): Use relative path as fallback of `$scoopdir`

### PR DESCRIPTION
**Pull request by HUMORCE**
#### Description

Use relative path as fallback of Scoop root directory.

#### Motivation and Context

Fallback to `~\scoop` cause non-standard installations of Scoop to not be recognized properly.

Relates to #5543 https://github.com/ScoopInstaller/Scoop/discussions/5542#discussioncomment-6199111

#### How Has This Been Tested?

Before:
```
PS C:\Users\WDAGUtilityAccount> scoop bucket list
Get-ChildItem : Cannot find path 'C:\Users\WDAGUtilityAccount\scoop\buckets' because it does not exist.
At C:\Users\WDAGUtilityAccount\中文\s p a c e\scoop\apps\scoop\current\lib\buckets.ps1:61 char:62
+ ... eneric.List[String]](Get-ChildItem -Path $bucketsdir -Directory).Name
+                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\WDAGUt...t\scoop\buckets:String) [Get-ChildItem], ItemNotFound
   Exception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

WARN  No bucket found. Please run 'scoop bucket add main' to add the default 'main' bucket.
```

After:
```
PS C:\Users\WDAGUtilityAccount> scoop bucket list

Name     Source                                Updated               Manifests
----     ------                                -------               ---------
main     ~\中文\s p a c e\scoop\buckets\main     6/18/2023 11:29:54 AM      1207
extras   ~\中文\s p a c e\scoop\buckets\extras   6/18/2023 11:29:54 AM      1880
versions ~\中文\s p a c e\scoop\buckets\versions 6/18/2023 11:29:56 AM       425
java     ~\中文\s p a c e\scoop\buckets\java     6/18/2023 11:29:55 AM       253
nuke     ~\中文\s p a c e\scoop\buckets\nuke     6/18/2023 11:29:54 AM       134


PS C:\Users\WDAGUtilityAccount> $env:SCOOP
PS C:\Users\WDAGUtilityAccount> scoop config
PS C:\Users\WDAGUtilityAccount>
```

#### Checklist:

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
- [x] I have ensured that I am targeting the `develop` branch.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.
- [x] I have added an entry in the CHANGELOG.

### CODE REVIEW

**Comment by niheaven** [comment]
Add it as fallback, not a replacement?

**Comment by HUMORCE** [comment]
> Add it as fallback, not a replacement?

I was doing like this, but all the fallbacks after it seem redundant. anyway, re-added.

**Review by niheaven — DISMISSED** [review]

**Comment by r15ch13** [comment]
While testing `scoop diag` I noticed that this will return the wrong path in my dev environment.
The scoop source is located in `X:\~projects\~powershell\scoop` and this change will set:
```
ScoopDir     = X:\
CacheDir     = X:\\cache
```

Before this change it would be set to
```
ScoopDir     = %USERPROFILE%\scoop
CacheDir     = %USERPROFILE%\scoop\cache
```

**Comment by HUMORCE** [comment]
The change is based on a standard installation. 
- Switch to standard directory structure
- Set `$env:SCOOP` manually before use dev environment

Non-standard dir structure may not be possible to test certain features, functions. e.g.

https://github.com/ScoopInstaller/Scoop/blob/3a3f41c556c044150d86f259c1e3583687b41929/lib/core.ps1#L1396-L1422

**Pull request merged**
