### PR TITLE
move all lib importing to the entry bin script

### LINKED ISSUE #3418: move all the libs importing to the entry bin script
I found that the mode of importing lib scripts from different libexec/lib scripts causes a really bad issue - some of the libs are imported and executed many times. This can cause other potential problems and effect performance probably.

**CASE**

1. In the `bin\scoop.ps1` entry bin script, it imported `lib\core.ps1` and `lib\bucket.ps1`::

https://github.com/lukesampson/scoop/blob/2db651c13a83f1c0ebb53723716efb5d96018fc0/bin/scoop.ps1#L7-L9

2. In the `libexec\scoop-bucket.ps1` script, it imported `lib\core.ps1` and `lib\bucket.ps1`:

https://github.com/lukesampson/scoop/blob/2db651c13a83f1c0ebb53723716efb5d96018fc0/libexec/scoop-bucket.ps1#L22-L23

3. And in the `lib\bucket.ps1` script, it also imported `lib\core.ps1`:

https://github.com/lukesampson/scoop/blob/2db651c13a83f1c0ebb53723716efb5d96018fc0/lib/buckets.ps1#L1

So, when I run `scoop bucket list`, the core lib `lib\core.ps1` is actually imported by **FOUR** times, and scoop will execute all of the code of `lib\core.ps1` by four times. You can simply add a line of code to verify it:

```diff
diff --git a/lib/core.ps1 b/lib/core.ps1
index 148f12539..6e6c54df9 100644
--- a/lib/core.ps1
+++ b/lib/core.ps1
@@ -10,6 +10,8 @@ if((test-path $oldscoopdir) -and !$env:SCOOP) {
     $scoopdir = $oldscoopdir
 }
 
+Write-Host "Hi"
+
 $globaldir = $env:SCOOP_GLOBAL, "$env:ProgramData\scoop" | Select-Object -first 1
 
 # Note: Setting the SCOOP_CACHE environment variable to use a shared directory
```

Then you will see 4 line of `Hi` printed before the bucket list.

```
$ scoop bucket list  
Hi
Hi
Hi
Hi
extras
main
```

Holy crap! And you will see all other libexec scripts are suffering this issue.

To be honest, I have realized this problem of scoop before I started to maintain pshazz. I have released a [patch](https://github.com/lukesampson/pshazz/commit/c1e1216a027ab33876e01ce95c52ae2d84b5f17a) for pshazz, which was also effected, by changing to import all libs from the `pshazz.ps1` entry script.

I didn't make patches for scoop because of the main bucket extraction event. And now I point out the issue to see if anyone has interest to fix this.

### PR DESCRIPTION
**Pull request by kiedtl**
Should fix #3418.

### CODE REVIEW

**Comment by kiedtl** [comment]
This PR completes tests successfully, and to the best of my knowledge everything is fine and no scripts/test/commands have been broken. There still may be quirks however.

Please add the `work-in-progress`/`please-review` tag.

/cc @r15ch13 @rasa @h404bi

**Comment by r15ch13** [comment]
Please base this PR on the develop branch. :smile:

**Comment by kiedtl** [comment]
> Please base this PR on the develop branch. 😄

Done.

**Comment by pratikpc** [comment]
Given that there are conflicts and the base branch has been removed, closing

**Comment by niheaven** [comment]
If the tweaks still work, please reopen a new PR, thanks. @kiedtl

**Pull request closed without merging**
