### PR TITLE
feat(scoop-update): Support `scoop update scoop`

### LINKED ISSUE #4940: [Feature] Handle `scoop update scoop`
### Is your feature request related to a problem? Please describe.

When I run `scoop update scoop`, it shows:

```
ERROR 'scoop' isn't installed correctly.
INFO  Please reinstall it or fix the manifest.
```

It should try to update Scoop, which makes more sense. This can be a proper way to ***update only Scoop itself without updating local buckets***.

### Describe the solution you'd like

Try to update Scoop itself when the app name (not parsed from a `<bucket>/<app>` string) for `scoop update` is `scoop` (case insensitive).

### PR DESCRIPTION
**Pull request by chawyehsu**
#### Description
Support `scoop update scoop`

#### Motivation and Context
Closes #4940
Relates to #4811

#### How Has This Been Tested?
```
scoop update
scoop update *
scoop update --all
scoop update scoop
scoop update scoop git
```

#### Checklist:

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
- [x] I have ensured that I am targeting the `develop` branch.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.
- [x] I have added an entry in the CHANGELOG.

### CODE REVIEW

**Comment by lewis-yeung** [comment]
The #4940 can be closed as well once this goes live.

**Review by rashil2000 — APPROVED** [review]

**Comment by rashil2000** [comment]
@chawyehsu any update on this?

**Comment by chawyehsu** [comment]
@rashil2000 Sorry for late response, I've not able to use the internet in the past days.

No update on that yet. But I suppose there needs be a condition checking of `$all` [here](https://github.com/ScoopInstaller/Scoop/blob/8018b93e3a6f909a686dc25d80c6004257334ae3/libexec/scoop-update.ps1#L339) similar to [this one](https://github.com/ScoopInstaller/Scoop/blob/8018b93e3a6f909a686dc25d80c6004257334ae3/libexec/scoop-update.ps1#L318).

**Comment by rashil2000** [comment]
Okay, I have added the fix

**Pull request merged**
