### PR TITLE
chore(release): Bump to version 0.2.3

### LINKED ISSUE #2141: Add cli help text and docs (faq) for installing and uninstalling specific versions
often you need to install or uninstall a specific version. the howto for this is missing.

the information for it is digged in an isuse https://github.com/lukesampson/scoop/issues/1957

there the comparision page is referenced https://github.com/lukesampson/scoop/wiki/Chocolatey-Comparison
this are all locations where i won't search normally.

to install a specific version:
```
scoop install curl@7.56.1
```

to uninstall a specific version i havn't found an info. can someone post the info here?

i would suggest to add this information to the faq page https://github.com/lukesampson/scoop/wiki/FAQ

also the cli command should output this info

```
scoop help install

Usage: scoop install <app> [options]
or
Usage: scoop install <app@version> [options]
...

To install an app with a specific version
    scoop install curl@7.56.1
```

same for `scoop uninstall`

### LINKED ISSUE #2381: Feature request - Show possible download size in `status` command
When doing a > scoop list command, it would be very helpful to show what apps have updates available, next to it's version number.  Yes, I know that doing scoop update shows new available, but when having many apps installed it's hard to keep track of all that, and the main update command only shows the most recent anyway, not ones it listed in the past.

Also, a upgrade command, like what apt-get does would help:
> scoop upgrade

much like the way apt-get upgrade works, it would be nice for scoop to get the list of upgradable apps, then have it show which ones will upgrade and the amount of data it may take.

Oh, speaking of, it may be helpful to actually put the file sizes in the scoop buckets and have the install command confirm the download first, showing the file size.  I have a data cap, so every byte counts.

### LINKED ISSUE #3188: scoop status says scoop is up to date when offline
To reproduce

1. Disconnect
2. Run `scoop status`
```
λ» scoop status
fatal: unable to access 'https://github.com/lukesampson/scoop/': Could not resolve host: github.com
Scoop is up to date.
Updates are available for: [...]
Everything is ok!
```
3. Reconnect
4. `scoop status` again
```
λ» scoop status
WARN  Scoop is out of date. Run 'scoop update' to get the latest changes.
Updates are available for: [...]
```

While the error implies that something went wrong while looking for an update (and any savvy user will correctly interpret it as "can't update without internet") saying that scoop is up to date is simply wrong - it's up to date *as far as the local scoop knows*.

scoop should only say that it's up to date when the update didn't encounter errors, or the error should be more verbose to invalidate the line below it.

### LINKED ISSUE #3489: Unable to save shortcut
I am having issues installing scoop apps on a windows 7 PC at a place of employment.
However my PC was set up in a weird way with respect to the networked drives.
As a result this prevented scoop from installing shortcuts to `Start Menu` because `Start Menu` is located on a networked drive in my user domain and this operation used badly formatted path for shortcuts. As far as I can tell the programs always installs on the local drive.

For an example of installing `git`
```
PS C:\Users\at17> scoop install git
Scoop uses Git to update itself. Run 'scoop install git' and try again.
Installing '7zip' (19.00) [64bit]
7z1900-x64.msi (1.7 MB) [=====================================================================================] 100%
Checking hash of 7z1900-x64.msi ... ok.
Extracting 7z1900-x64.msi ... done.
Linking ~\scoop\apps\7zip\current => ~\scoop\apps\7zip\19.00
Creating shim for '7z'.
ForEach-Object : Unable to save shortcut
"C:\Users\at17\Microsoft.PowerShell.Core\FileSystem::\fpsvr2\users7$\at17\Start Menu\Programs\Scoop Apps\7-Zip.lnk".
At C:\Users\at17\scoop\apps\scoop\current\lib\shortcuts.ps1:4 char:50
+     $shortcuts | Where-Object { $_ -ne $null } | ForEach-Object {
+                                                  ~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [ForEach-Object], FileNotFoundException
    + FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ForEachObjectCommand
```
My `Start Menu` is located in a networked drive that should begin with `\\fpsvr2` however the error shows that `\fpsvr2` was used instead. This path configuration is called UNC.

I am able to navigate to the `Start Menu`
```
PS C:\Users\at17> cd \\fpsvr2\users7$\at17\"Start Menu"\Programs
PS Microsoft.PowerShell.Core\FileSystem::\\fpsvr2\users7$\at17\Start Menu\Programs>
```
You can see in the destination directory that `Microsoft.PowerShell.Core\FileSystem` precludes the UNC path as shown in the error above.

Proposed solutions;
- Move `Start Menu` - I need to ask my IT dept to do this and there is no guarantee this will happen.
- Fix UNC path handling. The dropping of backslash needs to be fixed.
- Option to ignore making shortcuts in `Start Menu`. I have no idea how important  is `Start Menu` to operation of `scoop`. But this is a user facing feature and I have little use for this.

### LINKED ISSUE #3549: `scoop status` shows "Scoop is up to date." even though buckets don't have the latest changes.
Scoop should notice bucket's status as well as Scoop itself.

### Expected Behavior
```powershell
scoop status
#=>WARN  Scoop is out of date. Run 'scoop update' to get the latest changes.

scoop update
#=>....
scoop status
#=>Scoop is up to date.
#=>Updates are available for:
#=>    new-available-one is shown.
```

### Actual Behavior
```powershell
scoop status
#=>Scoop is up to date.
#=>Everything is ok!

scoop update
#=>....
scoop status
#=>Scoop is up to date.
#=>Updates are available for:
#=>    new-available-one is shown.
```

### LINKED ISSUE #3853: GitHub API rate limiting
While running scoop search multiple times, I've hit GitHub's API rate limit.

The message looks like this on scoop stderr:
```
invoke-webrequest : {"message":"API rate limit exceeded for IPADDRESS. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation    for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
```

`curl.exe -i https://api.github.com/` confirms it's a [60 req/hour limit](https://developer.github.com/v3/#rate-limiting) that's been hit.

Is there a way to authenticate with GitHub and get a bit more quota?

### LINKED ISSUE #3934: [Feature request] Import command
I think it would be nice to have a counterpart to `scoop export > file`, for example `scoop import file`. I know this can currently be achieved in an [alternative way][1], but still it would be more convenient to have a built-in command.

[1]: https://github.com/lukesampson/scoop/issues/1543#issuecomment-308894312

### LINKED ISSUE #4202: scoop search returns convertfrom-json : Invalid object passed in
Hi.
It seems similar errors have been reported, but I do not know exactly how to fix it.

```
PS C:\Users\tomas> scoop search sqlite
convertfrom-json : Invalid object passed in, ':' or '}' expected. (93): {
    "homepage": "https://github.com/JaDogg/expressPython",
    "license": "GPL-2.0-only",
<<<<<<< HEAD
    "version": "1.0.5",
    "url": "https://github.com/JaDogg/expressPython/releases/download/v1.0.5-beta/expressPython.7z",
=======
    "version": "1.0.55",
    "url": "https://github.com/JaDogg/expressPython/releases/download/v1.0.55-beta/expressPython.7z",
>>>>>>> 2159f8de0bdb636fa39c8d7200360af7915f414d
    "hash": "21b76552ff068ec602867f2cf1629d70f262cc04ce4484cd5fa7e3cf500938be",
    "bin": "expressPython.exe",
    "shortcuts": [
        [
            "expressPython.exe",
<<<<<<< HEAD
            "expressPython"
=======
            "express Python"
>>>>>>> 2159f8de0bdb636fa39c8d7200360af7915f414d
        ]
    ],
    "checkver": "github",
    "autoupdate": {
        "url": "https://github.com/JaDogg/expressPython/releases/download/v$version-beta/expressPython.7z"
    }
}
At C:\Users\tomas\scoop\apps\scoop\current\lib\manifest.ps1:10 char:45
+     Get-Content $path -raw -Encoding UTF8 | convertfrom-json -ea stop
+                                             ~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [ConvertFrom-Json], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

'dodorz' bucket:
    SQLiteExpert (5.3.5)
    Sqliteman (1.2.2)
```

Scoop is updated:

```
PS C:\Users\tomas> scoop update scoop
scoop: current (latest version)
Latest versions for all apps are installed! For more information try 'scoop status'
```

How shall I fix it?
Scoop rocks! 😄
Best Regards.

### LINKED ISSUE #4573: Reinstate 'current' junctions as a part of `scoop reset`
## Bug Report

**Package Name:** [name of package which has bug(s)]
scoop 

### Current Behaviour
Scoop uses a NTFS-directory-junction 'current` to point to the active-version of an app.
The NTFS junction is absolute.
Hence when scoop is ```xcopy```-ed into a VHDX and remounted on another windows-OS installation, the scoop root folder may not be in exactly the same location. (```xcopy /H /E /B /O /K /Y src dst```)
As a result powershell-function ```app_status()``` is not able to descend into the junction to retrieve the installed manifest,json and hence scoop list throws an error .

```
PS C:\vol\scoop_01\scoop\apps\scoop\current\lib> scoop list
Installed apps:

  7zip 21.06 *global* [main]
  adb  *global* *failed*
  android-sdk  *global* *failed*
  anki  *global* *failed*
  blender  *global* *failed*
  colortool  *global* *failed*
  doublecmd  *global* *failed*
```

The NTFS-directory-junction contains path from the other operating system, which is invalid on the new one.
Hence, errors.

### Expected Behaviour
Scoop should still work when copied for portability sake, instead of requiring user to install applications afresh

Perhaps instead of NTFS-junction, consider using 
- symbolic link ```mklink /d current 21.06```
Junction-links are always absolute, when copied point to the original mount path, environment variables cannot be embedded.

I want scoop to be
- located on a VHDX/partition etc,
- be mounted anywhere by any of a multi-boot multi-windows operating systems.

### Workaround
- mount the VHDX/partition in exactly same path on each windows operating system such as ```C:\vol\scoop_01\scoop ```
- include a small script to fix the junctions, in a manner similar to ```scoop reset```

### Possible Solution
- use symbolic links? 

### System details

**Windows version:** [e.g. 7, 8, 10]
Windows-10 and Windows-11

**OS architecture:** [e.g. 32bit, 64bit]
64-bit

**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
PS C:\Users\admin> echo $PSVersionTable

Name                           Value
PSVersion                      5.1.22000.282
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.282
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Additional software:** [(optional) e.g. ConEmu, Git]

### LINKED ISSUE #4606: [Feature] Allow passing array of app names to `checkver` utility
#### Is your feature request related to a problem? Please describe.

Original discussion here - https://github.com/ScoopInstaller/Main/pull/2871#issuecomment-987558132

When using authenticated requests, GitHub poses a limitation of 1000 API calls per hour. For buckets that have many GitHub-dependent manifests, this will be a problem.

#### Describe the solution you'd like
If the `checkver` utility is allowed to work on a set of app names, we can split the update process by passing each subset at a different hour so that we remain under the limit. 

#### Describe alternatives you've considered
- `checkver` can currently work on a single app, or an entire folder. Neither is feasible because passing individual app names at each workflow run would be too wasteful.
- We can't pause based on the `X-RateLimit-*` HTTP headers, because we will have pause for an hour every time, which is not very ideal. It's better to just have separate workflow runs each time.

### LINKED ISSUE #4615: [Feature] Highlight the available applications
#### Is your feature request related to a problem? Please describe.

Didn't find it yet.
#### Describe the solution you'd like

I think it's a little bit difficult to distinguish which applications are available to update when you "hold" some of them. If I run "scoop status" I'll get the status of all applications which includes those applications I don't want to upgrade. I don't know if I did it appropriately, but all I can do now is to check the applications line by line to make sure if I can run "scoop update *".
#### Describe alternatives you've considered

Currently a solution is I put every application that I don't want to upgrade to "hold" and then just simply run "scoop update *".
But I also think a little modification on the output of scoop status could be better and more user-friendly, which is:
1. Only display **outdated and "unheld"** applications in "Updates are available for:"
2. Highlight the **outdated and "unheld"** applications in "Updates are available for:"

### LINKED ISSUE #4840: [Feature] Display app's installation size in `scoop info`
#### Is your feature request related to a problem? Please describe.

I would like to be able to quickly find out how much space a currently installed application is taking on my computer while I am looking at the app's info in `scoop info`. Especially useful if I've just run out of space and want to check if I really need a certain app.

#### Describe the solution you'd like

When running `scoop info` another line would display the app's current size including all versions and any cached downloads. Something like the following:
```
❯ scoop info losslesscut

Name        : losslesscut
Description : Lossless trimming tool for video and audio files
Version     : 3.44.0
Bucket      : extras
...
App size    : 378 MB (471 MB including cache)
```
This would be useful for working out whether an app is worth keeping on smaller hard drives and might remind users to clean their cache.

However the drawback might be a slightly slower output for this command on all types of drives but especially HDDs. Probably negligible for most drives as it's just checking the size of two folders (app folder & cached items).

#### Describe alternatives you've considered

The user could always navigate to the app directory in File Explorer or run WizTree or a similar program but that would require multiple extra steps/programs. This could be good for staying in the terminal while installing/uninstalling old programs and running out of space for example.

### LINKED ISSUE #4852: [Feature] List app manifests from user added/official buckets.
#### Is your feature request related to a problem? Please describe.
At the moment it is not possible to list any applications from an official bucket or user added bucket.   
Say, a user adds a bucket and they installed an particular app(s) from it and want to see what other apps the bucket offers.     
I could find this useful in scenarios where a user wants to take a glance of available apps from an added bucket.           

#### Describe the solution you'd like

Say the user runs `scoop bucket apps <Bucket Name>`:
```ps
App  Version  Description
---  -------  -----------
App1  v1.0    This an application.
App2  v1.1    Another application.
```
It should list all given manifests/apps within the specified bucket, incase if all manifests' information cannot be fitted then a page system can be implemented.

So a user can run: `scoop bucket apps <Bucket Name> <Page Number>`.

A few ways how apps can be listed from a bucket.
1. Check for `.json` files in a bucket.
2. Look for `.json` files which follow the scoop manifest format and list them as listable apps.

#### Describe alternatives you've considered

You can use Windows/File Explorer to explore the bucket and check out app manifests but this is extremely inconvenient.
Bringing this directly into the terminal make viewing apps from buckets from accessible.

### LINKED ISSUE #5005: [Bug] Errors on installing/updating an app that creates a shortcut
### Current Behavior

When I tried to install/update an app that creates a shortcut, Scoop ran into a series of errors showing `Cannot find a provider with the name '[System.IO.Path]'`, `Cannot bind argument to parameter 'Path' because it is null`, etc.

### Expected Behavior

No error happens.

### Additional context/output

Terminal output: (taking `scoop update 7zip` as an example)

```
7zip: 21.07 -> 22.00
Updating one outdated app:
Updating '7zip' (21.07 -> 22.00)
Downloading new version
Starting download with aria2 ...
Download: Download Results:
Download: gid   |stat|avg speed  |path/URI
Download: ======+====+===========+=======================================================
Download: fccdcf|OK  |    91KiB/s|C:/Users/LY/scoop/cache/7zip#22.00#https_7-zip.org_a_7z2200-x64.msi
Download: Status Legend:
Download: (OK):download completed.
Checking hash of 7z2200-x64.msi ... ok.
Uninstalling '7zip' (21.07)
Removing shim '7z.shim'.
Removing shim '7z.exe'.
Unlinking ~\scoop\apps\7zip\current
Installing '7zip' (22.00) [64bit]
Loading 7z2200-x64.msi from cache.
Extracting 7z2200-x64.msi ... done.
Linking ~\scoop\apps\7zip\current => ~\scoop\apps\7zip\22.00
Creating shim for '7z'.
New-Item: C:\Users\LY\scoop\apps\scoop\current\lib\core.ps1:453
Line |
 453 |          New-Item -Path $dir -ItemType Directory | Out-Null
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find a provider with the name '[System.IO.Path]'.

Convert-Path: C:\Users\LY\scoop\apps\scoop\current\lib\core.ps1:455
Line |
 455 |      Convert-Path -Path $dir
     |      ~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot find a provider with the name '[System.IO.Path]'.

Convert-Path: C:\Users\LY\scoop\apps\scoop\current\lib\shortcuts.ps1:28
Line |
  28 |  … onvert-Path $(ensure [System.IO.Path]::Combine([Environment]::GetFold …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Cannot bind argument to parameter 'Path' because it is null.

OperationStopped: C:\Users\LY\scoop\apps\scoop\current\lib\shortcuts.ps1:57
Line |
  57 |      $wsShell.Save()
     |      ~~~~~~~~~~~~~~~
     | Unable to save shortcut "C:\7-Zip.lnk".

Creating shortcut for 7-Zip (7zFM.exe)
Persisting Codecs
Persisting Formats
Running post_install script...
'7zip' (22.00) was installed successfully!
Notes
-----
Add 7-Zip as a context menu option by running: "C:\Users\LY\scoop\apps\7zip\current\install-context.reg"
```

This is most likely related to a freshly merged PR #4410.

### Possible Solution

None for the time being.

### System details

- **Windows version:** 11
- **OS architecture:** 64bit
- **PowerShell version:** 7.2.4

### Scoop Configuration

```json
{
  "lastUpdate": "2022-06-21T18:57:09.3466368+08:00",
  "SCOOP_REPO": "https://github.com/ScoopInstaller/Scoop",
  "SCOOP_BRANCH": "develop",
  "aria2-max-connection-per-server": 16,
  "aria2-split": 16,
  "aria2-min-split-size": "1M",
  "aria2-warning-enabled": false,
  "debug": true,
  "manifest_review": true
}
```

### LINKED ISSUE #5027: Add --all flag to "scoop cache rm" subcommand
## Feature Request

Similar to #4887.

Add an alias for `scoop cache rm *` which would be `scoop cache rm --all`

#### Is your feature request related to a problem? Please describe.
Due to me using non standard shell (bash) on Windows, the `*` symbol gets expanded and Scoop won't see the symbol as an argument to the command.

### LINKED ISSUE #5033: [Bug] Import Command Display Abnormality
When trying to import a exported json which doesn't have a config property:
图片
I Suppose there are two issues here:
1. Nullity check
2. Trying to add buckets that already exist (exist in both the import file and scoop)

### PR DESCRIPTION
**Pull request by niheaven**
### Features

- **chore:** Add missing -a/--all param to all commands (#5004)
- **scoop-status:** Check bucket status, improve output (#5011)
- **scoop-info:** Show app installed/download size (#4886)
- **scoop-import:** Import a Scoop installation from JSON (#5014, #5034)

### Bug Fixes

- **chore:** Update help documentation (#5002, #5029)
- **decompress:** Handle split RAR archives (#4994)
- **shortcuts:** Fix network drive shortcut creation (#4410, #5006)

### Code Refactoring

- **scoop-search:** Output PSObject, use API token (#4997)

### Builds

- **checkver,auto-pr:** Allow passing file path (#5019)
- **checkver:** Exit routine earlier if error (#5025)
- **json:** Update Newton.Json to 13.0.1 (#5026)

### Tests

- **typo:** Fix typo ('formated' -> 'formatted') (#4217)

## Close Issues

- Closes #3489
- Closes #5005
- Closes #4202
- Closes #4573
- Closes #4852
- Closes #3853
- Closes #2141
- Closes #4840
- Closes #3549
- Closes #4615
- Closes #3188
- Closes #5027
- Closes #3934
- Closes #4606
- Closes #5033
- Closes https://github.com/ScoopInstaller/Scoop/security/dependabot/1

## Credits

Thanks to the following contributors (ordered by PR merging time):

@cyingfan @rashil2000 @igitur @tech189 @issaclin32 @niheaven @zStruCat

### CODE REVIEW

**Comment by niheaven** [comment]
Should this go to v0.3.0 or v0.2.3?

And hope not missing issues that could be closed.

**Comment by tech189** [comment]
I'm not sure releasing my PR should close #2381 yet as it only partially solves that problem. It is only for one app at a time, rather than showing the overall pending download size in `scoop status` or `scoop update`.

**Comment by niheaven** [comment]
> I'm not sure releasing my PR should close #2381 yet as it only partially solves that problem. It is only for one app at a time, rather than showing the overall pending download size in `scoop status` or `scoop update`.

Remove that issue, and yes, it seems not to be fixed and needs further investigation.

**Comment by niheaven** [comment]
Could be checked and reviewed, ready to go now.

**Comment by rashil2000** [comment]
Need a bit of time to check #5034

**Review by rashil2000 — APPROVED** [review]

**Review by issaclin32 — APPROVED** [review]

**Comment by rashil2000** [comment]
@niheaven may I merge this time? 😅

**Comment by niheaven** [comment]
> @niheaven may I merge this time? 😅
> 
> The strategy is 'Rebase and Merge', right?

Let's go, the merge strategy is 'Merge pull request', the first one.

Rebasing is disabled for all our repos.

**Comment by niheaven** [comment]
Yes, and it is synced now (this should be done manually)

**Comment by rashil2000** [comment]
Ah okay, understood

**Pull request merged**
