### PR TITLE
Add supporting scoop-clone.ps1 command

### PR DESCRIPTION
**Pull request by r15ch13**
Allows cloning git repositories without a complete git installation.

```pwsh
.\scoop-clone.ps1 -Repository "https://github.com/r15ch13/Excavator" -Directory "D:\ExcavatorTest"
```

It could be used to remove skip the unpacking of `archive.zip` on installation.

### CODE REVIEW

**Comment by Ash258** [comment]
Why not move it to separate repository under @scoopinstaller with appveyor pipeline for runing / build / unit tests.

**Comment by r15ch13** [comment]
Yup will do that.

**Comment by r15ch13** [comment]
Done: https://github.com/scoopinstaller/scoop-clone

Added a script that automatically generates release notes (including commits since the last release and a list of contributors) to the `build.ps1`.
This could be added to `scoop` itself and the other supporting tools (once they have their own repo) as well.

```powershell
Write-Output 'Generating release notes ...'
#region GitHub release notes
$previousRelease = (Invoke-RestMethod -Uri "https://api.github.com/repos/$env:APPVEYOR_REPO_NAME/releases/latest?access_token=$env:GITHUB_ACCESS_TOKEN")
$compare = (Invoke-RestMethod -Uri "https://api.github.com/repos/$env:APPVEYOR_REPO_NAME/compare/$($previousRelease.target_commitish)...$env:APPVEYOR_REPO_COMMIT`?access_token=$env:GITHUB_ACCESS_TOKEN")
$releaseNotes = "## Release Notes`n#### Version [$env:APPVEYOR_REPO_TAG_NAME](https://github.com/$env:APPVEYOR_REPO_NAME/tree/$env:APPVEYOR_REPO_TAG_NAME)`n"

if($null -ne $compare.commits -and $compare.commits.Length -gt 0) {
    $releaseNotes += "`nCommit | Description`n--- | ---`n"
    $contributions = @{}
    $compare.commits | Sort-Object -Property @{Expression={$_.commit.author.date};} -Descending | ForEach-Object {
        $commitMessage = $_.commit.message.Replace("`r`n"," ").Replace("`n"," ");
        if ($commitMessage.ToLower().StartsWith('merge') -or
            $commitMessage.ToLower().StartsWith('merging') -or
            $commitMessage.ToLower().StartsWith('private')) {
                continue
        }
        $releaseNotes += "[``$($_.sha.Substring(0, 7))``](https://github.com/$env:APPVEYOR_REPO_NAME/tree/$($_.sha)) | $commitMessage`n"
        $contributions.$($_.author.login)++
    }
    $releaseNotes += "`nContributor | Commits`n--- | ---`n"
    $contributions.GetEnumerator() | Sort-Object -Property @{Expression={$_.Value}} -Descending | ForEach-Object {
        $releaseNotes += "@$($_.Name) | $($_.Value)`n"
    }
} else {
    $releaseNotes += "There are no new items for this release."
}

$env:GITHUB_RELEASE_NOTES = $releaseNotes
Write-Output $releaseNotes
#endregion
```

**Comment by Ash258** [comment]
Nice 👋

We could move this conversation into #3066, #3003

**Comment by Ash258** [comment]
I think this is pretty much for https://github.com/scoopinstaller/install

For this repo it is obsolete when new installer is done.

**Pull request closed without merging**
