### PR TITLE
fix(schema): Add 'license' definition

### PR DESCRIPTION
**Pull request by niheaven**
#### Description

**HOTFIX**: Fix AppVeyor error

#### Motivation and Context

Relates to https://github.com/ScoopInstaller/Scoop/pull/4594#issuecomment-1001076388

#### Checklist:

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
- [ ] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

**Comment by niheaven** [comment]
This PR should be synced to 'develop' after merging.

**Comment by rashil2000** [comment]
Still failing. See https://github.com/rashil2000/Extras fork, and the run here: https://ci.appveyor.com/project/rashil2000/extras/builds/42008819/job/t5t6l8atgtgbhu8u 

Maybe you need to update /test/fixtures/manifest/invalid_wget.json too?

**Comment by niheaven** [comment]
It's a different failure. I'll check it.

**Comment by niheaven** [comment]
Tested locally

image

**Comment by rashil2000** [comment]
It passes now - https://ci.appveyor.com/project/rashil2000/extras/build/job/wwea6pp4s9yh9x3r

**Review by rashil2000 — APPROVED** [review]

**Comment by rashil2000** [comment]
@issaclin32 this one slightly high priority, can you approve it if you're around?

**Review by issaclin32 — APPROVED** [review]

**Pull request merged**
