### PR TITLE
fix(core): Use Invoke-Command instead of Invoke-Expression

### PR DESCRIPTION
**Pull request by niheaven**
#### Description

Get rid of `Invoke-Expression` that may cause problems and may leak some code.

Ref: https://github.com/MicrosoftDocs/PowerShell-Docs/wiki/The-case-for-and-against-Invoke-Expression

#### Motivation and Context

- Closes https://github.com/ScoopInstaller/Extras/issues/8494
- Closes https://github.com/ScoopInstaller/Extras/issues/8498
- Closes https://github.com/ScoopInstaller/GithubActions/pull/8

#### How Has This Been Tested?

- `scoop -v`
- `scoop update`
- `scoop install gnupg`
- `.\bin\checkver i*` in 'extras' bucket
- `.\test.ps1`

#### Checklist:

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
- [x] I have ensured that I am targeting the `develop` branch.
- [x] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.
- [x] I have added an entry in the CHANGELOG.

### CODE REVIEW

**Comment by rashil2000** [comment]
There are multiple instances of such commands:
```pwsh
$currentBranch = Invoke-Command { git -C "$currentdir" branch }
```

Why not just replace them with:
```pwsh
$currentBranch = git -C "$currentdir" branch
```

**Comment by niheaven** [comment]
`Invoke-Command` run the script block in a child scope, so it should be safer and could improve readability.

**Comment by rashil2000** [comment]
Scope doesn't matter for git (and other similar external commands) right? On the other hand, I feel it hampers readability because it makes it seem like git commands need special handling. 

For strings containing PowerShell code, it makes sense.

**Comment by niheaven** [comment]
Great, let's try and see if there are unexpected bugs.

**Comment by niheaven** [comment]
Removed `Invoke-Command` before `git`, and tested okay here.

**Review by rashil2000 — APPROVED** [review]

**Pull request merged**
