### PR TITLE
refactor(git): Use 'git -C' to specify the work directory instead of 'Push-Location'/'Pop-Location'

### LINKED ISSUE #4358: Working directory changed if we cancelled `scoop update` via `CTRL+C`
Sometimes I only want to use the `scoop status` command to quickly check apps versions, but it becomes `scoop update` if the buckets are outdated. I try to cancel the job, but the working directory stays on the bucket directory.

Scoop uses `Push-Location` to change the working directory to the bucket directory and fetch it from the remote repo. 

To fix this, simply use the `finally` block:

Change

``` ps1
Push-Location $path
...
Pop-Location
```

To

``` ps1
Push-Location $path
try {
   ...
} finally { Pop-Location }
```

### LINKED ISSUE #4675: [Feature Request] Improve `Update failed` error message
#### Current Behavior

Issuing scoop update, gives the following
Updating Scoop...
Update failed.
#### Expected Behavior

scoop itself is updated
### System details

**Windows version:** [e.g. 7, 8, 10]
10
**OS architecture:** [e.g. 32bit, 64bit]
64bit
**PowerShell version:** [output of `"$($PSVersionTable.PSVersion)"`]
5.1.18362.1801
**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

Empty file

### PR DESCRIPTION
**Pull request by HUMORCE**
#### Description
no longer using `Push-Location` to change work directory before executing git operations

#### Motivation and Context

Fixes #4358 
Fixes #4675

send ^C(SIGINT) will change current directory to bucket path, when scoop is updating buckets.

solve:
using command options `-C` to specify the work directory for git, then no longer need to change the \<work directory> with `Push-Location` and `Pop-Location`.

#### How Has This Been Tested?

before:
```
PS C:\Users\WDAGUtilityAccount> scoop update
Updating Scoop...
Updating 'main' bucket...
^C
PS C:\Users\WDAGUtilityAccount\scoop\buckets\main>
```
after:
```
PS C:\Users\WDAGUtilityAccount> scoop update
Updating Scoop...
Updating 'main' bucket...
^C
PS C:\Users\WDAGUtilityAccount>
```

tested on PS 5.1 and PS Core 7.2 in sandbox, the changes will not affect other areas.

#### Checklist:

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
- [x] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by HUMORCE** [comment]
and what type of this PR should be?

**Comment by rashil2000** [comment]
Fixes https://github.com/ScoopInstaller/Scoop/issues/4358 https://github.com/ScoopInstaller/Scoop/issues/4675

**Comment by HUMORCE** [comment]
thanks about that

**Comment by rashil2000** [comment]
Looks good. 

The functions `git_fetch`, `git_pull` and `git_checkout` can be removed from lib/git.ps1 now, since they're not being used anywhere.

**Review by rashil2000 — APPROVED** [review]

**Pull request merged**
