### PR TITLE
style: Formatting the entire project

### PR DESCRIPTION
**Pull request by HUMORCE**
correct(? not sure)/consistent casing, indent, whitespaces ..

formatting code when viewing and learning the project.

there was a self-review, locally.

#### Checklist:
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
- [x] I have updated the documentation accordingly.

### CODE REVIEW

**Review by rasa — APPROVED** [review]

**Comment by niheaven** [comment]
Do not make such big PR, style the part that you think should be optimized.

**Comment by rashil2000** [comment]
Yes, I feel so too. We can make formatting changes along with bug fixes/refactors, as we have been doing for past few days. It is easier to review that way, and also keeps git history clean.

**Comment by HUMORCE** [comment]
most of the code has not been changed for more than 3 years.

yea, we can say that they are stable, but it affects the viewing too also.

**Comment by niheaven** [comment]
Yes, we all know the code base is old, so only change each part or each style per PR, and don't style the code that does not meet some criteria. And for easily lookup line history and function origin, do not style code that has not been functionally changed.

The basic rules: one PR for one thing, refactoring is better than styling.

**Comment by rasa** [comment]
I respectfully disagree. I find having consistent styling helps onboard those new to the project. I think the benefits of consistency, and cleaving to a standard (whatever standard we choose), outweigh the problem of polluting our git history. Thank you for the contribution @HUMORCE.

**Comment by niheaven** [comment]
@HUMORCE One PR for one file and one styling, e.g., correct casing in core.ps1 (plus expand param names), then correct casing in other file (bin and libexec has fewer files, they could be styled together), then other tweaks.

I'm against huge PR which is hard to review, and unorgnized git history submitted. Squash some commits and only keep meanful commit logs.

Thank you for your contribution @HUMORCE and hope you could split and reorgnize and submit separately again.

**Comment by HUMORCE** [comment]
> I respectfully disagree. I find having consistent styling helps onboard those new to the project. I think the benefits of consistency, and cleaving to a standard (whatever standard we choose), outweigh the problem of polluting our git history.

So we need to specify a standard for the codebase now.


> hope you could split and reorgnize and submit separately again.

I will, mixed code styles reduces the readability, and affects contributors to choose the style they need to use in this codebase.

**Comment by niheaven** [comment]
> So we need to specify a standard for the codebase now.

Yes, start a discussion in this repo and you may paste the recommended vscode styling options and let's discuss and decide which to adopt.

**Pull request closed without merging**
