### PR TITLE
fix(core): Ensure manipulating config with UTF8 encoding

### LINKED ISSUE #4629: Aria2 and git does not support non-ASCII paths
Errors will occur when aria2 is enabled, and `SCOOP_DIR` contains non-ASCII chars (for example, `C:\Users\小李\scoop`). Aria2 will save the file in a **gibberish/[mojibake](https://en.wikipedia.org/wiki/Mojibake)** path such as `C:\Users\�������������\scoop`.

upstream discussion: https://github.com/aria2/aria2/issues/1417

We cannot expect **aria2** to fix this problem in a short time, but there are 2 solutions I can think of:

**(1) Ban aria2 if it is the case**
If `SCOOP_DIR` contains non-ASCII chars. Then:
Set `aria2-enabled` to false, and forbid setting it to True (also give user a message like `aria2 cannot be enabled because scoop path 'C:\Users\小李\scoop' contains non-ASCII characters`

or, **(2) Create junctions** 
If `SCOOP_DIR` contains non-ASCII chars, then:
Convert the path with **URL encode**:
`[System.Web.HttpUtility]::UrlEncode('C:\Users\小李\scoop\cache')` -> This will equal to `C%3a%5cUsers%5c%e5%b0%8f%e6%9d%8e%5cscoop%5ccache`

Create a junction `C:\users\Public\scoop-cache-C%3a%5cUsers%5c%e5%b0%8f%e6%9d%8e%5cscoop%5ccache` that points to `C:\Users\小李\scoop\cache`.

After doing this, we can set Aria2 to save the file in `C:\users\Public\scoop-cache-C%3a%5cUsers%5c%e5%b0%8f%e6%9d%8e%5cscoop%5ccache`, and it should work fine.

Asking for your opinions:
@rasa @niheaven @chawyehsu @rashil2000

### PR DESCRIPTION
**Pull request by chawyehsu**
#### Description
Use utf8 encoding in scoop's and aria2's config

#### Motivation and Context

Fixes #4629

[1]: https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-content?view=powershell-5.1
[2]: https://docs.microsoft.com/en-us/dotnet/api/system.io.file.writealltext

#### How Has This Been Tested?
New unit tests introduced.

#### Checklist:

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
- [x] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

**Review by niheaven — COMMENTED** [review]
Maybe `New-Item` is a better choice.

I found in its docs that: ([`-ItemType File`](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-item?view=powershell-5.1#parameters))

> When you create a file using this method, the resulting file is encoded as UTF-8 without a byte-order-mark (BOM).

**Comment by niheaven** [comment]
I'll check it tomorrow.

**Comment by niheaven** [comment]
@chawyehsu It is a bug of Pester/PS5 when test file contains non-ASCII characters. Using `[Regex]::Unescape` to avoid it.

Although change `[System.IO.File]::ReadAllText` to `[System.IO.File]::ReadAllLines` to keep consistence.

**Review by niheaven — APPROVED** [review]

**Review by chawyehsu — COMMENTED** [review]
LGTM

**Pull request merged**
