### PR TITLE
feat(scoop-prefix): remove unused imports and functions. Load when required

### PR DESCRIPTION
**Pull request by pratikpc**
Unused imports removed:-
1. manifest.ps1
2. buckets.ps1

Unused function removed:-
1. reset_aliases:- We do not use aliases here.

Load when required
1. help needs to be loaded only when app is not specified
2. core needs to be loaded only when app is specified

Gains:-
1. Improved speed.

### CODE REVIEW

**Comment by rashil2000** [comment]
Retarget to develop branch. Master is for release.

**Comment by rashil2000** [comment]
@niheaven would be able to suggest more on this.

**Comment by niheaven** [comment]
@pratikpc Except for #4013 #4342 #4492, other merged PRs in `master` are only for text works. The recent commit (#3518) in `develop` is on the main develop line of scoop itself.

There are many feathers under development and they all should be committed into `develop` and tested by advanced users (incl. maintainers), only critical hotfixes that may affect normal users should be merged directly into `master` and synchronized to `develop`.

These commits that ahead `develop` now could be merged into `develop` after new commits in `master` and `develop` are all carefully tested, and then we can sync the branches and merge new PRs into `develop` and test them again.

**Comment by pratikpc** [comment]
That makes sense. 

Although we really should first rebase develop on master so that we may not end up with future conflicts.

**Pull request closed without merging**
