### PR TITLE
refactor(shim, scoop-cache) use -join instead of '+' to concatenate strings

### PR DESCRIPTION
**Pull request by zStruCat**
use "-join" to improve performance

#### Checklist:

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
- [x] I have ensured that I am targeting the `develop` branch.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.
- [ ] I have added an entry in the CHANGELOG.

### CODE REVIEW

**Comment by rashil2000** [comment]
Do you have some benchmarks?

**Comment by zStruCat** [comment]
No

**Comment by niheaven** [comment]
Then this should be kept as is

**Comment by rashil2000** [comment]
Hmm yes, unless there's a problem or bottleneck, we can skip on such optimizations for keeping readability

**Pull request closed without merging**
