### PR TITLE
feat(ci): Setup github actions as test ci

### PR DESCRIPTION
**Pull request by chawyehsu**
#### Description
Setup Github Actions CI

#### Motivation and Context
Migration from appveyor

#### How Has This Been Tested?
~demo: https://github.com/chawyehsu/scoop/actions/runs/1682023136~

https://github.com/ScoopInstaller/Scoop/actions/runs/1682034804

#### Checklist:

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
- [x] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

**Comment by chawyehsu** [comment]
Might break downstream bucket tests that still use appveyor, investigating...

**Comment by rashil2000** [comment]
> Might break downstream bucket tests that still use appveyor, investigating...

We will migrate all our buckets CI to GH Actions too. 

But for third-party buckets, instead of removing Appveyor-specific code, why not put both? We could detect if the CI is Appveyor or GitHub (or third case, local installation) and run stuff conditionally. This way third-party bucket maintainers won't have to migrate.

**Comment by rashil2000** [comment]
Also I think `.github/workflows/ci.yml` would be a more precise name.

**Comment by chawyehsu** [comment]
Replaced by #4655

**Pull request closed without merging**
