### PR TITLE
fix(core): Use correct path in 'bash'

### LINKED ISSUE #5952: [Bug] using any package gives error
#### Current Behavior
using any package gives error

scoop install neofetch
Installing 'neofetch' (7.1.0) [64bit] from 'main' bucket
neofetch (333.6 KB) [=========================================================================================] 100%
Checking hash of neofetch ... ok.
Linking ~\scoop\apps\neofetch\current => ~\scoop\apps\neofetch\7.1.0
Creating shim for 'neofetch'.
'neofetch' (7.1.0) was installed successfully!
'neofetch' suggests installing 'git'.

neofetch
/bin/bash: C:\Users\nirgr\scoop\apps\neofetch\current\neofetch: No such file or directory

#### Expected Behavior
work as expected

#### Additional context/output
I have WSL and Cygwin installed

### System details

**Windows version:** Win 11 Version 23H2 (0S Build 22631.3447)

### PR DESCRIPTION
**Pull request by niheaven**
#### Description

Since Windows 11 add default `bash.exe` in system folder, there may be bugs when using linux apps. This PR fixes it by converting Windows path using proper utils (`wslpath` in WSL and `cygpath` in Cygwin/MSYS2).

#### Motivation and Context

- Closes #5952
- Closes https://github.com/ScoopInstaller/Extras/issues/13385
- Related to https://github.com/ScoopInstaller/Extras/pull/13342

#### How Has This Been Tested?

By running neofetch under Powershell, CMD, WSL, Cygwin and MSYS2.

#### Checklist:

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
- [x] I have ensured that I am targeting the `develop` branch.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.
- [x] I have added an entry in the CHANGELOG.

### CODE REVIEW

**Comment by yoBlastic** [comment]
That was quick!

how do I apply the fix?

**Comment by niheaven** [comment]
You could use `scoop config SCOOP_BRANCH develop` to switch to develop branch, and use `scoop reset xxx` to reset your shim.

**Comment by yoBlastic** [comment]
i dont know what 1/2 that stuff is. I dont wanna flood the board with noob questions, but thanks anyway, ill see what I can figure out.

**Comment by yoBlastic** [comment]
> scoop config SCOOP_BRANCH develop

"WARN scoop: 'config' isn't a scoop command. See 'scoop help'"

even scoop help doesnt work

**Comment by niheaven** [comment]
Hmm, `scoop config` error? It's scoop's internal command, please check your input, or try `scoop config` and see if it could output sth.

**Comment by yoBlastic** [comment]
> Hmm, `scoop config` error? It's scoop's internal command, please check your input, or try `scoop config` and see if it could output sth.

same thing....  but again, im a noob.  not dumb, but noob/ish nonetheless.

**Comment by niheaven** [comment]
Okay, please check if there's `scoop-config.ps1` in your `Scoop\apps\scoop\current\libexec\` dir.

**Comment by yoBlastic** [comment]
yes, it is there.

**Comment by niheaven** [comment]
Then `scoop config` will be there, too... What's about other command? e.g. `scoop reset xxx` or `scoop shim list`?

**Comment by yoBlastic** [comment]
Screenshot 2024-06-19 023421

**Comment by niheaven** [comment]
Could you download `https://[raw.githubusercontent.com/ScoopInstaller/Scoop/master/bin/scoop.ps1](https://raw.githubusercontent.com/ScoopInstaller/Scoop/master/bin/scoop.ps1)` and put it under `Scoop\apps\scoop\current\bin` (with overwrite), then try again?

**Comment by yoBlastic** [comment]
no change

**Comment by yoBlastic** [comment]
> Could you download `https://[raw.githubusercontent.com/ScoopInstaller/Scoop/master/bin/scoop.ps1](https://raw.githubusercontent.com/ScoopInstaller/Scoop/master/bin/scoop.ps1)` and put it under `Scoop\apps\scoop\current\bin` (with overwrite), then try again?

Thanks again in your attempt to help me out.  Seems I had a secondary issue (https://github.com/ScoopInstaller/Scoop/issues/3050) copying the "current" folder and naming it "new" and now my commands are being recognized, scoop help , scoop config are working.

image

**Comment by yoBlastic** [comment]
result:

image

**Comment by niheaven** [comment]
You should run `scoop update` after `scoop config`. Okay, now it should work fine.

**Comment by yoBlastic** [comment]
> You should run `scoop update` after `scoop config`. Okay, now it should work fine.

its working!  though, neofetch is showing my ubuntu WSL and now windows.  whatever

what you waked me through seems to be a manual fix for just that app/shim, im I understanding that right?

im having a similar issue now tying to install a CAB file for some hardware im messing with.... related or no? pic:

image

**Comment by niheaven** [comment]
Unrelated IMO...

**Comment by maherm** [comment]
This change does now suppress any output to sterr. That seems like a bug. stderr is a valid output channel and you are losing information when the output on this channel is suppressed. e.g. a wrong or missing argument will usually trigger an output on stderr and maybe some usage instructions too. Now, the script just terminates without any output.

**Pull request merged**
