### PR TITLE
chore(core): Deprecate tls1 and tls1.1

### PR DESCRIPTION
**Pull request by neheb**
Both of these are deprecated.

### CODE REVIEW

**Comment by neheb** [comment]
The interesting thing on my Windows 8.1 machine is that TLS1.3 is available. So .Net 4.8 is installed?

**Comment by neheb** [comment]
Interestingly enough,

 ```
if (!($isNewerNetFramework -and $isSystemDefault)) {
```

evaluates to true on my machine. The weird thing is, [System.Net.ServicePointManager]::SecurityProtocol is set to SystemDefault. It shouldn't be evaluating to true and overwriting SystemDefault.

**Comment by neheb** [comment]
Done.

**Comment by niheaven** [comment]
I'm not familiar with TLS and .net, but for Win 7 and .net 4.5, should this cause errors?

And if we update minimal requirement to .net 4.7, this TLS sector could be removed IMO.

**Comment by neheb** [comment]
.net 4.5 supports tls 1.2. There's no change here other than removing 1.0 and 1.1.

I will say that even this is not enough to fix https://github.com/ScoopInstaller/Main/issues/3593 . Maybe the issue needs to be reported to curl developers.

**Review by chawyehsu — APPROVED** [review]

**Comment by neheb** [comment]
Done.

**Review by chawyehsu — APPROVED** [review]

**Review by niheaven — APPROVED** [review]

**Pull request merged**
