### PR TITLE
feat(supporting): Update Json to 12.0.3, Json.Schema to 3.0.14

### PR DESCRIPTION
**Pull request by niheaven**
## VirusTotal

[shim](https://www.virustotal.com/gui/file/9726c3a429009a5b22bd92cb8ab96724c670e164e7240e83f27b7c8b7bd1ca39)
[validator](https://www.virustotal.com/gui/file/40a70bee96d108701f8f2e81392f9b79fd003f1cb4e1653ad2429753153fd7ee)

### 12.0.3

- New feature - Added support for nullable reference types
- New feature - Added KebabCaseNamingStrategy
- Change - Package now uses embedded package icon
- Fix - Fixed bug when merging JToken with itself
- Fix - Fixed performance of calling ICustomTypeDescriptor.GetProperties
- Fix - Fixed serializing Enumerable.Empty and empty arrays on .NET Core 3.0
- Fix - Fixed deserializing some collection types with constructor
- Fix - Fixed deserializing IImmutableSet to ImmutableHashSet instead of ImmutableSortedSet
- Fix - Fixed deserializing IImmutableDictionary to ImmutableDictionary instead of ImmutableSortedDictionary
- Fix - Fixed deserializing into constructors with more than 256 parameters
- Fix - Fixed hang when deserializing JTokenReader with preceding comment
- Fix - Fixed JSONPath scanning with nested indexer
- Fix - Fixed deserializing incomplete JSON object to JObject
- Fix - Fixed using StringEnumConverter with naming strategy and specified values

### 12.0.2

- New feature - Added MissingMemberHandling to JsonObjectAttribute and JsonObjectContract
- New feature - Added constructor to JTokenReader to specify initial path
- New feature - Added JsonProperty.IsRequiredSpecified
- New feature - Added JsonContract.InternalConverter
- Change - Moved embedded debug symbols in NuGet package to a symbol package on NuGet.org
- Fix - Fixed deserializing nullable struct collections
- Fix - Fixed memory link when serializing enums to named values
- Fix - Fixed error when setting JsonLoadSettings.DuplicatePropertyNameHandling to Replace

### 12.0.1

- New feature - Added NuGet package signing
- New feature - Added Authenticode assembly signing
- New feature - Added SourceLink support
- New feature - Added constructors to StringEnumConverter for setting AllowIntegerValue
- New feature - Added JsonNameTable and JsonTextReader.PropertyNameTable
- New feature - Added line information to JsonSerializationException
- New feature - Added JObject.Property overload with a StringComparison
- New feature - Added JsonMergeSettings.PropertyNameComparison
- New feature - Added support for multiple Date constructors with JavaScriptDateTimeConverter
- New feature - Added support for strict equals and strict not equals in JSON Path queries
- New feature - Added EncodeSpecialCharacters setting to XmlNodeConverter
- New feature - Added trace message for serializing to non-writable properties
- New feature - Added support for NamingStrategy to StringEnumConverter
- New feature - Added JsonLoadSettings.DuplicatePropertyNameHandling setting
- Change - JTokenReader now uses JsonReader.DateTimeZoneHandling setting for date values
- Change - Excluded TargetSite when serializing Exceptions without SerializableAttribute
- Change - Changed StringEnumConverter.ctor(bool camelCaseText) to obsolete
- Change - Changed StringEnumConverter.CamelCaseText to obsolete
- Fix - Fixed incorrect overflow when reading decimal values from JSON
- Fix - Fixed error message when trying to deserialize an abstract serializable type
- Fix - Fixed parsing decimals from a string with an exponent
- Fix - Fixed losing DateTime.Kind when deserializing ISO date strings
- Fix - Fixed calling constructors with ref and in parameters
- Fix - Fixed rare race condition in name table when serializing
- Fix - Fixed unhelpful exception message when unable to convert JSON value to DateTime
- Fix - Fixed error when deserializing empty array in DataTable
- Fix - Fixed deserializing empty string to empty byte array
- Fix - Fixed blank extension data values with required properties and deserializing with constructor
- Fix - Fixed ignored values being set in extension data when deserializing
- Fix - Fixed comparing equal integer and floating point values in JSON Path
- Fix - Fixed BsonReader when reading multiple content
- Fix - Fixed setting extension data with existing key
- Fix - Fixed including array attribute in XML with namespaces when converting JSON to XML
- Fix - Fixed error when serializing ref struct properties by excluding them from serialization

### 3.0.14

- New feature - Add support for draft 2019-09
- New feature - Enable nullable references
- Fix - Fix writing empty dependency collection
- Fix - Fix error when unevaluated is combined conditional keywords
- Fix - Fix generating schemas for ReadOnlyDictionary types
- Fix - Fix deserializing null with JSchemaConverter
- Fix - Fix error when CompositeContext combined with if/then/else
- Fix - Fix using JsonValidator with certain JTokenReader output
- Fix - Fix validating duplicate key in dependencies and dependentSchemas

### 3.0.13

- No changes

### 3.0.12

- New feature - Add JSchema.ToString settings overload
- Change - Remove portable target
- Fix - Fix dependencies not being written
- Fix - Fix nested root schema references
- Fix - Fix self referencing schema when schema id already has hash
- Fix - Fix writing dependencies

### 3.0.11

- New feature - Added Source Link support
- New feature - Provide additional info for invalid schema IDs
- Fix - Fixed ISO date string enum values being parsed as dates
- Fix - Fixed a performance issue when serializing large JSchema objects
- Fix - Fixed validating null string token from JTokenReader
- Fix - Fixed validating JsonReader with multiple pieces of content
- Fix - Fixed JSchemaReferenceHandling flags
- Fix - Fixed validating property name with enumeration
- Fix - Fixed require properties validation error display incorrect properties
- Fix - Fixed StringEnumGenerationProvider when enum containing duplicate values
- Fix - Fixed error messages from nested schemas in else/then not being listed

### CODE REVIEW

**Comment by niheaven** [comment]
Should this be closed 'cos extracting validator?

**Comment by niheaven** [comment]
The validator and shim are still shipped with scoop, and Newtonsoft.Json is used for parsing manifests.

**Comment by niheaven** [comment]
Does anyone know why will using Newtonsoft.Json v13.0.1 produce following error?

```powershell
Add-Type: D:\Scoop\apps\scoop\current\lib\json.ps1:96:5
Line |
  96 |      Add-Type -Path "$psscriptroot\..\supporting\validator\bin\Newtons …
     |      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not load file or assembly 'Newtonsoft.Json, Version=13.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed'.
```

**Comment by pratikpc** [comment]
It would be so much easier for us if NewtonSoft started distributing DLLs via PSGallery officially.

**Pull request merged**
