### PR TITLE
Another attempt to improve the search performance

### LINKED ISSUE #4239: Improve Search Performance
https://github.com/shilangyu/scoop-search has changed my experience with scoop, the slow search has always been one of my pain points as a user.

I'd be willing to PR improvement to the search engine to incorporate the lessons learnd here if there is interest.

### PR DESCRIPTION
**Pull request by r15ch13**
#### Description
This is another attempt to improve the local search performance.
- Not using the `manifest()` function
- Use only one loop over `$apps`
- Push results to `$list` directly
- Use `[System.IO.File]::ReadAllText()` instead of `Get-Content`

#### Motivation and Context

Closes #4239

Relates to #4818

#### How Has This Been Tested?

```pwsh
Measure-Command { scoop search telegram }
Measure-Command { .\bin\scoop.ps1 search telegram }
```

image

#### Checklist:

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
- [x] I have ensured that I am targeting the `develop` branch.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.
- [x] I have added an entry in the CHANGELOG.

### CODE REVIEW

**Comment by r15ch13** [comment]
See conversation in https://github.com/ScoopInstaller/Scoop/pull/5324
Had to recreate the PR because I messed up my branch ...

**Comment by cigh033** [comment]
would love to see this merged as this drastically reduces search time 👍

**Review by rashil2000 — DISMISSED** [review]

**Comment by rashil2000** [comment]
@r15ch13 LGTM - just one small hitch - this is not a bug fix but a performance improvement (in the Changelog)

**Comment by justrainer** [comment]
With this now merged, when can an update to main be expected? I notice that there has not been an update for nearly a year.
Alternatively, how can I build / use from the develop branch? I really want to get my hands on this specific change.

**Comment by rashil2000** [comment]
You can use the `develop` branch using this code:
```
scoop config SCOOP_BRANCH develop
scooop update
```

**Pull request merged**
