### PR TITLE
chore: Update Nonportable bucket URL

### PR DESCRIPTION
**Pull request by issaclin32**
* related: https://github.com/ScoopInstaller/Nonportable/issues/1

* Updates `buckets.json` and `README.md`.

* Since I could not contact @TheRandomLabs to transfer the bucket, old users will still be using `github.com/TheRandomLabs/scoop-nonportable`. We probably need a mechanism to help users to migrate to the new bucket.

### CODE REVIEW

**Comment by niheaven** [comment]
Target to 'develop' and there's a bug fix version bump soon.

**Review by niheaven — APPROVED** [review]

**Comment by rashil2000** [comment]
@issaclin32 @niheaven weren't ScoopInstaller/Nonportable and ScoopInstaller/GithubActions forks of other repos? I can't see the fork relation now...

**Comment by issaclin32** [comment]
> @issaclin32 @niheaven weren't ScoopInstaller/Nonportable and ScoopInstaller/GithubActions forks of other repos? I can't see the fork relation now...

I sent a ticket to Github to detach the repos.

**Comment by rashil2000** [comment]
Oh, okay, thanks for the info!

**Pull request merged**
