### PR TITLE
Enable commands in the bucket

### PR DESCRIPTION
**Pull request by nueko**
this PR enable bucket commands in the /commands directory
usage:
`scoop php/info $args`

### CODE REVIEW

**Comment by nueko** [comment]
`scoop help php/info` also works like what expected.
>what this would be used for?

let's say it is about php
bucket creator can add commands to start the app, de/activate functionalities, etc...
eg: 
`scoop php/start [7.1]` to run `php-cgi.exe -b 127.0.0.1:9000 -c php.ini
`scoop php/start nginx`
`scoop php/dismod redis [7.1]`
`scoop php/enmod redis [7.1]`

**Comment by lukesampson** [comment]
Okay thanks. I think we can use this, but I'm not sure how I feel about using `scoop` as the entry point for these bucket commands—it still feels like there should be more separation between what's Scoop and what could be completely separate functionality. Maybe it's just a matter of doing it as `scoop run [bucket]/[cmd]`?

What do you think, @r15ch13? How does it fit in with what you were planning? Is there overlap with a `scoop services` command?

**Comment by nueko** [comment]
it is not about starting services.
see the last snippet, it enables/disables php module. another example, maybe to create adservers or create root.key

**Comment by lukesampson** [comment]
Okay, but `php-cgi.exe -b 127.0.0.1:9000 -c php.ini` is very similar to starting a service.

**Comment by nueko** [comment]
it's just example :smile

**Comment by lukesampson** [comment]
Understood. I think it's a good idea and I'm sure we can get something working but we might need to tweak it a bit. We need to move slowly when making changes to core functionality like this. And it'd be good to coordinate with @r15ch13 because he seems to be working on similar areas.

**Comment by rasenplanscher** [comment]
> Maybe it's just a matter of doing it as `scoop run [bucket]/[cmd]`?

I think, you're spot-on here.
That would be a lot cleaner, and going without `run` would not help all that much in reducing typing...

**Comment by rashil2000** [comment]
Closing as stale

**Pull request closed without merging**
