### PR TITLE
feat(chore): Add missing -a/--all param to all commands

### PR DESCRIPTION
**Pull request by rashil2000**
#### Checklist:

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
- [x] I have ensured that I am targeting the `develop` branch.
- [x] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.
- [x] I have added an entry in the CHANGELOG.

### CODE REVIEW

**Comment by niheaven** [comment]
LGTM for 'cache' and 'reset', but for 'virustotal', the `-e` sounds strange, and why not remove `arch` and let `-a` stands for `--all`?

Users check not-installed app's URLs for both 32bit and 64bit, right?

**Comment by rashil2000** [comment]
> Users check not-installed app's URLs for both 32bit and 64bit, right?

I'm not really sure about this.

For consistency I can remove the `arch` flag, and use the system's default architecture only. What should we do?

**Comment by niheaven** [comment]
> For consistency I can remove the `arch` flag, and use the system's default architecture only. What should we do?

I prefer to check both for not installed apps, and only check used architecture if installed.

**Review by niheaven — DISMISSED** [review]
LGTM

**Pull request merged**
