### PR TITLE
build(ci): Use cache in GitHub Actions

### PR DESCRIPTION
**Pull request by niheaven**
#### Description

Use ~https://github.com/actions/cache~ https://github.com/potatoqualitee/psmodulecache to cache PowerShell modules in GitHub Actions. (Really not happy while working with https://github.com/actions/cache)

#### Motivation and Context

PowerShell modules installation is the most time-consuming step of CI test, this fix tries to skip them.

It also skips modules installation if there're ones.

#### How Has This Been Tested?

~I don't find an effective way to test the PR, but it seems to work~

~From CI results below, it found cache, but doesn't use them. Maybe a little more tweak are needed.~

Use https://github.com/potatoqualitee/psmodulecache to cache PowerShell Modules, it works fine as this PR's two commits.

#### Checklist:

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
- [x] I have updated the documentation accordingly.
- [ ] ~I have updated the tests accordingly.~

### CODE REVIEW

**Comment by niheaven** [comment]
Should we remove CI running trigger by `push` if every change in Scoop Core must submit a PR? For this one, GHA runs four tests of which two are unneeded.

**Comment by rashil2000** [comment]
> For this one, GHA runs four tests of which two are unneeded.

I think this happens only when a PR is opened from Scoop core itself. If someone from outside forks and sends a PR it will run twice.

**Comment by niheaven** [comment]
I mean, since a PR is required, is it needed for other pushed branches to pass CI test? This test should be run only when a PR is submitted.

**Comment by rashil2000** [comment]
Hmm, yeah, makes sense

**Comment by rashil2000** [comment]
Will it be possible to cache stuff for other workflows too, like pull request/issue handler, hash fix/404 error handler, `/verify` etc.? Currently it installs scoop, sets up 7zip etc. on each run and it takes a lot of time.

**Comment by niheaven** [comment]
Caching scoop is not preferred since we need CI to test modified scoop code. For decompressing tools, current CI won't fetch them until needed, see https://github.com/ScoopInstaller/Scoop/blob/5f407ca43452f6025accdfb58490d6ee100bf31b/test/bin/test.ps1#L30-L33 and https://github.com/ScoopInstaller/Scoop/blob/5f407ca43452f6025accdfb58490d6ee100bf31b/test/bin/test.ps1#L42-L45

**Comment by rashil2000** [comment]
> ... we need CI to test modified scoop code.

Why would this be required for issues/PR handlers?

**Comment by niheaven** [comment]
> Why would this be required for issues/PR handlers?

You mean tests in bucket repo? Yes, scoop code should be cached there, and a proper hash should be found to make sure it is in `HEAD` of 'master' branch.

**Comment by rashil2000** [comment]
> You mean tests in bucket repo? 

Yes, I meant for the buckets itself

**Comment by niheaven** [comment]
I'll take some time to check the probability. It should be cacheable, IMO.

**Review by chawyehsu — APPROVED** [review]

**Pull request merged**
