### PR TITLE
Rename checkver_token to gh_token and SCOOP_CHECKVER_TOKEN to SCOOP_GH_TOKEN

### PR DESCRIPTION
**Pull request by astelmachonak-nydig**
- Rename `checkver_token` to `gh_token` and `SCOOP_CHECKVER_TOKEN` to `SCOOP_GH_TOKEN`
- Follow up fix for https://github.com/ScoopInstaller/Scoop/pull/4254 (filtering null input in dl function when private_hosts is not set in config)

#### Checklist:

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
- [x] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

**Comment by rashil2000** [comment]
Additionally, can you replace all instances of `checkver_token` with `gh_token` (4 in total) in this PR?

**Comment by astelmachonak-nydig** [comment]
@rashil2000 done, please review

**Review by rashil2000 — APPROVED** [review]

**Comment by rashil2000** [comment]
https://github.com/ScoopInstaller/GithubActions/blob/bd73d5711c4ad072c73e17d41b592e57d71892c6/src/Action/Scheduled.psm1#L24

This also needs to be updated then, I'll do it once this is merged

**Comment by rashil2000** [comment]
> https://github.com/ScoopInstaller/GithubActions/blob/bd73d5711c4ad072c73e17d41b592e57d71892c6/src/Action/Scheduled.psm1#L24
> 
> This also needs to be updated then, I'll do it once this is merged

This can't be done yet. We will have to wait for a new release.

**Comment by niheaven** [comment]
This tends to be a `refactor`, not a `feature`, will change the `CHANGELOG` next time.

**Comment by astelmachonak-nydig** [comment]
> This tends to be a `refactor`, not a `feature`, will change the `CHANGELOG` next time.

I was debating between these two and decided to go with feature since this change affects the users (env var change, configuration parameter change). However if refactoring in the sense you use it allows "breaking" changes, I agree this is refactoring.

**Comment by niheaven** [comment]
Yes, adding a "breaking change" at the top of release notes for this one is a better idea, since it is UX change, right? 😄

**Comment by astelmachonak-nydig** [comment]
> Yes, adding a "breaking change" at the top of release notes for this one is a good idea, since it is UX change, right? 😄

Exactly. I searched in the changelog for something like this, but didn't find...

**Comment by niheaven** [comment]
> Exactly. I searched in the changelog for something like this, but didn't find...

Because we haven't had such BREAKING CHANGES since we have changelog...

**Pull request merged**
