### PR TITLE
 Implement SourceForge checkver functionality

### PR DESCRIPTION
**Pull request by se35710**
In it's most simple form:
```
    "checkver": "sourceforge",
```
This will find the project name from homepage, or if that fails, from the manifest name.

A more comples example:
```
    "checkver": {
        "sourceforge": {
            "project": "pmt",
            "path": "/pngcrush-executables"
        }
    },
```
Here we provide the project name, and a path into the files section (to limit number of downloads). `project` is optional and only needed if `homepage` or manifest name is not equal to the SourceForge project name.

Regex can be applied as normal, on the `checkver` property, or on the `re` property. The default regex is `"(?:.*)?\/(?:v)?([\d.]+)\/"` plus the path to the project.

### CODE REVIEW

**Comment by rasa** [comment]
@r15ch13 if you like this work, I will fix the conflicts.

**Comment by niheaven** [comment]
It should be noticed that `editorconfig` is not suitable for this method, since it didn't release windows binary from 0.12.1.

**Comment by rashil2000** [comment]
@se35710 any updates?

**Comment by se35710** [comment]
@rashil2000 Working on it now, slowly...

**Comment by se35710** [comment]
Replaced with #4560

**Pull request closed without merging**
