### PR TITLE
fix(cleanup): Remove apps other than current version

### LINKED ISSUE #4663: [Bug] cleanup cannot delete old version
#### Current Behavior

After scoop cleanup *, there were nothing cleaned up.
```
$ scoop cleanup *
Everything is shiny now!
```
#### Expected Behavior

Should clear old version, such like 
```
Removing pe-bear: _0.5.5.2.old
```
I found all the directories like "_$version.old" cannot be deleted.
#### Possible Solution

I changed [function Get-InstalledVersion in `lib\versions.ps1`](https://github.com/ScoopInstaller/Scoop/blob/5602083868ed04224ea8edf1ff0c3a2a3f6588b9/lib/versions.ps1#L98)
```
return $versions | Where-Object { ($_ -ne 'current') -or ($_ -like '_*.old*') }
```
### System details

**Windows version:** 10

**OS architecture:** 64bit

**PowerShell version:** 7.2.1

**Additional software:** [(optional) 
Current Scoop version:
56020838 (HEAD -> master, tag: 2021-12-26, origin/master, origin/HEAD) fix(schema): Add 'license' definition (#4596)

### PR DESCRIPTION
**Pull request by niheaven**
#### Description

It will remove all subdir except for `current` and its target version.

#### Motivation and Context

Closes #4663

#### How Has This Been Tested?

Before:
image

After:
image

#### Checklist:

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
- [x] I have updated the documentation accordingly.
- [ ] ~I have updated the tests accordingly.~

### CODE REVIEW

**Comment by rashil2000** [comment]
@zhangchaoza can you confirm if this fixes your issue? 
To test this, temporarily switch to the PR branch:
```
scoop config SCOOP_BRANCH fix-cleanup
scoop update
scoop cleanup *
```

To go back to the stable (release) branch:
```
scoop config SCOOP_BRANCH master
scoop update
```

**Comment by niheaven** [comment]
I'll change the logic to resolve https://github.com/ScoopInstaller/Scoop/issues/4648#issuecomment-1013717258

**Comment by zhangchaoza** [comment]
> @zhangchaoza can you confirm if this fixes your issue? To test this, temporarily switch to the PR branch:
> 
> ```
> scoop config SCOOP_BRANCH fix-cleanup
> scoop update
> scoop cleanup *
> ```
> 
> To go back to the stable (release) branch:
> 
> ```
> scoop config SCOOP_BRANCH master
> scoop update
> ```

It works, and thank you for your working.@niheaven

**Comment by niheaven** [comment]
@zhangchaoza I'm sorry, but could you test this PR again? I've changed the logic.

Also pin @HUMORCE

**Comment by HUMORCE** [comment]
failed installations can be removed with `scoop-cleanup` now. and i think `scoop-list` should be split for installed and failed apps, after these changes. OR just replace `Installed apps:` with `Managed apps:`

**Pull request merged**
