### PR TITLE
feat(scoop-config): Allow 'hold_update_until' be set manually

### PR DESCRIPTION
**Pull request by niheaven**
#### Description

Rename `update_until` to `hold_update_until` and allow it be set manually in the format such as `YYYY/MM/DD`, `YYYY-MM-DD` or any other forms that accepted by [[System.DateTime]::Parse()](https://docs.microsoft.com/dotnet/api/system.datetime.parse?view=netframework-4.5#StringToParse)

#### Motivation and Context

- Relates to https://github.com/ScoopInstaller/Scoop/pull/5089#issuecomment-1211876041

#### How Has This Been Tested?

image
image

#### Checklist:

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
- [x] I have ensured that I am targeting the `develop` branch.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.
- [x] I have added an entry in the CHANGELOG.

### CODE REVIEW

**Comment by niheaven** [comment]
@r15ch13 This should be what you need, right? 😄

**Comment by r15ch13** [comment]
Yes :smile:

But there is no need for exception handling if `TryParse()` is used.

```pwsh
[datetime]$hold_update_until = New-Object DateTime
$a = [System.DateTime]::TryParse($cfg_value, $null, [System.Globalization.DateTimeStyles]::AssumeLocal, 
[ref]$hold_update_until)
```

It simply returns True/False

**Comment by yi-Xu-0100** [comment]
@niheaven @r15ch13 Why not try to parse `$hold_update_until` when use `scoop config hold_update_until <wrong_value>`? And reply the docs link when parse failed. 😊

**Comment by r15ch13** [comment]
```pwsh
function is_scoop_onhold() {
    $hold_update_until = get_config hold_update_until
    if ($null -eq $hold_update_until) {
        return
    }
    
    [datetime]$parsed_date = New-Object DateTime
    if([System.DateTime]::TryParse($hold_update_until, $null, [System.Globalization.DateTimeStyles]::AssumeLocal, [ref]$parsed_date)) {
        if ((New-TimeSpan $parsed_date).TotalSeconds -lt 0) {
            warn "Skipping self-update until $($parsed_date.ToLocalTime())..."
            warn "If you want to update Scoop itself immediately, use 'scoop unhold scoop; scoop update'."
            return $true
        }
    } else {
        warn "'hold_update_until' has been set in the wrong format and was removed."
        warn "If you want to disable Scoop self-update for a moment, use 'scoop hold scoop' or 'scoop config hold_update_until <YYYY-MM-DD>/<YYYY/MM/DD>'."
        set_config hold_update_until $null | Out-Null
    }
}
```
And then use `is_scoop_onhold()` inside `update_scoop()`


```pwsh
function update_scoop($show_update_log) {
    # snip

    if(is_scoop_onhold()) {
        return
    }

    # snip
}
```

**Comment by r15ch13** [comment]
> @niheaven @r15ch13 Why not try to parse `$hold_update_until` when use `scoop config hold_update_until <wrong_value>`? We can reply to the user with the docs link when parse failed, otherwise the calculated actual time when parse succeeded. 😊

Checking the user input is also a good idea. But that requires a rework of `scoop config` in general` :smile:

**Comment by niheaven** [comment]
Wow, yes, I was trying to use `TryParse` but didn't understand what the `[ref]` is...

I'll fix the code tomorrow using above code and test it again (maybe it is been tested? 🤣 )

**Comment by niheaven** [comment]
All done @r15ch13

**Review by r15ch13 — APPROVED** [review]

**Pull request merged**
