### PR TITLE
fix(scoop-virustotal): Adjust `json_path` parameters to retrieve correct analysis stats

### LINKED ISSUE #6042: [Bug] scoop-virustotal gives an error instead of report after release 0.5.0
#### Current Behavior

Scoop-virustotal is not usable anymore after release 0.5.0. Instead of an VirusTotal report we get just errors. It seems some parameters have not been marshalled properly.

#### Expected Behavior

Scoop-virustotal should provide a VirusTotal report for any package specified.

#### Additional context/output

```powershell
C:\Users\jkniiv> scoop virustotal eza
Property 'malicious' not valid on JArray.
Property 'suspicious' not valid on JArray.
Property 'timeout' not valid on JArray.
Property 'undetected' not valid on JArray.
WARN  main/eza: VirusTotal request failed: Cannot convert value "[1113159]" to type "System.Int32". Error: "The input string '[1113159]' was not in a correct format."
C:\Users\jkniiv> scoop info eza

Name        : eza
Description : A modern, maintained replacement for ls, built on exa.
Version     : 0.18.20 (Update to 0.18.21 available)
Bucket      : main
Website     : https://github.com/eza-community/eza
License     : MIT
Updated at  : 1.7.2024 11:28:55
Updated by  : github-actions[bot]
Installed   : 0.18.19
              0.18.20
Binaries    : eza.exe | exa.exe

C:\Users\jkniiv> scoop virustotal persepolis
Property 'malicious' not valid on JArray.
Property 'suspicious' not valid on JArray.
Property 'timeout' not valid on JArray.
Property 'undetected' not valid on JArray.
WARN  extras/persepolis: VirusTotal request failed: Cannot convert value "[115695080]" to type "System.Int32". Error: "The input string '[115695080]' was not in a correct format."
C:\Users\jkniiv> scoop virustotal doggo
Property 'malicious' not valid on JArray.
Property 'suspicious' not valid on JArray.
Property 'timeout' not valid on JArray.
Property 'undetected' not valid on JArray.
WARN  main/doggo: VirusTotal request failed: Cannot convert value "[4096151]" to type "System.Int32". Error: "The input string '[4096151]' was not in a correct format."
``` 

### System details

**Windows version:** 10 ver. 22H2 (build 19045.4529)

**OS architecture:** 64bit

**PowerShell version:** 7.4.3

**Additional software:** [(optional) e.g. ConEmu, Git]

#### Scoop Configuration

```json
{
  "virustotal_api_key": "002redacted",
  "aria2-enabled": true,
  "last_update": "2024-07-05T21:31:57.8912335+03:00",
  "scoop_repo": "https://github.com/lukesampson/scoop",
  "scoop_branch": "master"
}
```

Additionally, $env:SCOOP has been set to 'C:\scoop'.

### PR DESCRIPTION
**Pull request by Lutra-Fs**
#### Description

This PR aims to fix the error introduced in https://github.com/ScoopInstaller/Scoop/issues/5920. It uses the $single arguments in json_path to correctly extract the data instead, as previously they are enclosed with square brackets.

#### Motivation and Context

- Closes #6042 

- Related to #5957

#### How Has This Been Tested?

Tested using Powershell 7
```
scoop virustotal eza
main/eza: 0/64, see https://www.virustotal.com/gui/file/0c5e596c990e15cbc04dce52ed9629cc8adc9c967d5e79534d6ddea020323cc4
scoop virustotal -a
main/1password-cli: 0/67, see https://www.virustotal.com/gui/file/761f2aa0f8907b397940cb69d9514efbcc4c67de6d64426e99a542edc60d615c
main/7zip: 0/64, see https://www.virustotal.com/gui/file/eb94db7341e59f1871a4d4f60165563f1881e33aef093b7d8427651c2a0f4b6f
```

#### Checklist:

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
- [x] I have ensured that I am targeting the `develop` branch.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.
- [x] I have added an entry in the CHANGELOG.

### CODE REVIEW

**Comment by niheaven** [comment]
Please add the changlog entry

**Comment by niheaven** [comment]
Please sign all your commits next time, thanks.

**Comment by Lutra-Fs** [comment]
> Please sign all your commits next time, thanks.

I use another PC to do the rebase work, which I did not configure GPG sign. Will check it next time.

**Comment by Lutra-Fs** [comment]
Any chance to publish a hotfix version? I can see some people are complaining about the bug

**Pull request merged**
