### PR TITLE
fix(scoop-search): Remove redundant 'bucket/' in search result

### LINKED ISSUE #4772: [Bug] Remote Search Result Display Redundant
When searching from added buckets fails to generate results, scoop will search known but not added buckets online (in this case, games). However:
pic
"bucket" here is redundant.

### PR DESCRIPTION
**Pull request by zStruCat**
Closes #4772 
- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).

### CODE REVIEW

**Comment by zStruCat** [comment]
> Actually, the `bucket/` is not redundant. Sometimes multiple buckets have same package, so we specify `scoop install <bucket>/<app>` to install a particular app.
> 
> It would be better to replace the `bucket/` word by the actual name of the bucket, like `games/`.

The display of searched manifests is divided into several section,  each belonging to a particular bucket with its name displayed at the begining of the section, so perhaps there's no need for it to appear again in the manifest.

pid

**Comment by rashil2000** [comment]
Then we should leave it as it is, because the instruction `scoop install <bucket>/<app>` is still important

**Comment by zStruCat** [comment]
Also, it's consistent with the display format of local bucket
图片

Off the topic, i do think `scoop install bucket/app` is important. To be more precise, i feel that the form of bucket/app@version as a consistent input query is vital. Unfortunately, different command of scoop has acted inconsistently. For instance, search and list doesn't support bucket/app yet......

**Comment by rashil2000** [comment]
I think a common middle ground would be to make this result:
```
Results from other known buckets...
(add them using 'scoop bucket add <name>')

'nonportable' bucket:
    bucket/qttabbar-np
```

into
```
Results from other known buckets...
(add them using 'scoop bucket add <name>')

'nonportable' bucket (install using 'scoop install nonportable/<app>'):
    qttabbar-np
```

This will make it consistent with local bucket results.

**Comment by zStruCat** [comment]
> I think a common middle ground would be to make this result:
> 
> ```
> Results from other known buckets...
> (add them using 'scoop bucket add <name>')
> 
> 'nonportable' bucket:
>     bucket/qttabbar-np
> ```
> 
> into
> 
> ```
> Results from other known buckets...
> (add them using 'scoop bucket add <name>')
> 
> 'nonportable' bucket (install using 'scoop install nonportable/<app>'):
>     qttabbar-np
> ```
> 
> This will make it consistent with local bucket results.

This is exactly what my commit do.
pic

**Comment by zStruCat** [comment]
> Notice the additional text beside the bucket header, that is not present in your commit

But `scoop install` cannot install app from a known but not added bucket. It results in the following:
`
WARN  Bucket 'games' not installed. Add it with 'scoop bucket add games' or 'scoop bucket add games <repo>'.
Couldn't find manifest for '0ad' from 'games' bucket.
`

**Comment by rashil2000** [comment]
> But scoop install cannot install app from a known but not added bucket. It results in the following:

Instruction for adding other known buckets is already given at the beginning of results, right

**Comment by zStruCat** [comment]
changed accordingly

**Comment by niheaven** [comment]
You should make `bucket/` optional since it is not required in bucket repo.

**Comment by rashil2000** [comment]
> You should make `bucket/` optional since it is not required in bucket repo.

Do you mean the hint should only be shown for not added buckets?

**Comment by niheaven** [comment]
> Do you mean the hint should only be shown for not added buckets? 

No, I means the regex. Not all bucket repo has manifest files in 'bucket' subfolder, they may be put in root folder and that's scoop's original bucket structure.

**Comment by zStruCat** [comment]
> > Do you mean the hint should only be shown for not added buckets?
> 
> No, the regex. Not all bucket repo has manifest files in 'bucket' subfolder, they may be put in root folder and that's scoop's original bucket structure.

First, currently the remote search only search the remote 'known' bucket, i.e. main, extras, nirsoft, etc, all of which put manifests under bucket directory.
Secondly, if scaning all files, we won't be able to distinguish between a manifest and a normal json file without downloading and check them with the schema. Is the time-cost here acceptable?

**Comment by zStruCat** [comment]
Any other issues?

**Comment by niheaven** [comment]
I've tweaked some code and now LGTM.

**Review by niheaven — APPROVED** [review]

**Pull request merged**
