### PR TITLE
refactor(scoop-shim): Use `getopt` to parse arguments

### PR DESCRIPTION
**Pull request by lewis-yeung**
### Description

Use `getopt` to parse arguments, which avoids some problems. BTW, add some logic and tweak some error messages.

### Motivation and Context

These problems will be resolved:

1. For example, run `scoop shim add myapp ''`, the second parameter (`<command_path>`) gets an empty value, so Scoop will throw an exception, which is not so friendly. :

	```
	Cannot validate argument on parameter 'Name'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
	```

2. For example, run `scoop shim list *`, the regex pattern `*` is invalid, so Scoop will throw an exception, which is not so friendly. :

	```
	Invalid pattern '*' at offset 1. Quantifier {x,y} following nothing.
	```

3. The `-g`/`--global` option cannot be parsed in `scoop shim ...`. See #5094.

### How Has This Been Tested?

Now with this:

1. `scoop shim add myapp ''` shows an error:

	```
	ERROR <command_path> must be specified for subcommand 'add'
	```

2. `scoop shim list *` shows an error:

	```
	ERROR: Invalid pattern: *
	```

3. To create a local shim `myapp` with `arg` and `--global` as arguments:

	```powershell
	scoop shim add myapp 'D:\path\myapp.exe' '--' arg --global
	```

	Note that we have to use a QUOTED command option terminator (`'--'`) in PowerShell CLI.

4. To create a global shim `myapp` with `arg` as the argument:

	```powershell
	scoop shim add -g myapp 'D:\path\myapp.exe' arg
	```

No major changes to other subcommands.

### Checklist:

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
- [x] I have ensured that I am targeting the `develop` branch.
- [x] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.
- [x] I have added an entry in the CHANGELOG.

### CODE REVIEW

**Comment by niheaven** [comment]
I'll review it in a few days, thank you for the PR.

**Comment by lewis-yeung** [comment]
@niheaven Any suggestions? :)

**Comment by niheaven** [comment]
Just see my commit, now LGTM.

**Comment by lewis-yeung** [comment]
Shall we move on?

**Review by niheaven — APPROVED** [review]

**Pull request merged**
