### PR TITLE
scoop-help.ps1: keeping only the first found command to print it's re…

### PR DESCRIPTION
**Pull request by AntonOks**
…lated help

I'm wondering if no one else has this error... if so, I may have to many additional commands added ;)
Anyhow, I'm getting the below error message... and with a  quick hack to unsure only the first found "command" Key is kept, all works fine in my case...

ERROR I get:
```powershell
λ  scoop
Usage: scoop <command> [<args>]

Some useful commands are:
MethodInvocationException: C:\Users\<user>\scoop\apps\scoop\current\libexec\scoop-help.ps1:29
Line |
  29 |          $commands.add("$command ", $summary) # add padding
     |          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Exception calling "Add" with "2" argument(s): "Item has already been added. Key in dictionary: 'search '  Key being added: 'search '"


alias           Manage scoop aliases
bucket          Manage Scoop buckets
bucket-origin   Show the scoop buckets and their "git origin" info
cache           Show or clear the download cache
cache-rm-all    Clear the download cache for all apps
cache-show-all  Show the download cache for all apps
checkup         Check for potential problems
cleanup         Cleanup apps by removing old versions
cleanup-all     Cleanup all apps by removing old versions
config          Get or set configuration values
create          Create a custom app manifest
depends         List dependencies for an app
export          Exports (an importable) list of installed apps
help            Show help for a command
hold            Hold an app to disable updates
home            Opens the app homepage
info            Display information about an app
info-all        Display information about apps in all buckets
install         Install apps
list            List installed apps
list-all        List apps in all buckets
prefix          Returns the path to the specified app
reset           Reset an app to resolve conflicts
search          Search available apps
search-info     Search available apps and display information about each app
status          Show status and check for new app versions
unhold          Unhold an app to enable updates
uninstall       Uninstall an app
update          Update apps, or Scoop itself
update-all      Update all apps and scoop
virustotal      Look for app's hash on virustotal.com
which           Locate a shim/executable (similar to 'which' on Linux)

Type 'scoop help <command>' to get help for a specific command.
```

### CODE REVIEW

**Comment by rashil2000** [comment]
I do not get this error when I type just `scoop` (in either Windows PowerShell or PowerShell Core).

I wonder what source you're using for the repo - since I can see some additional commands in your help section. Are those custom aliases?

**Comment by pratikpc** [comment]
Could you share the content of the libexec folder and your Scoop shims folder?

I am only interested in files which start with "scoop-"

**Comment by AntonOks** [comment]
> Could you share the content of the libexec folder and your Scoop shims folder?
> 
> I am only interested in files which start with "scoop-"

Thanks for your interest / help...

1. libexec 
```powershell
λ  ls .\libexec\

    Directory: C:\Users\<user>\scoop\apps\scoop\current\libexec

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          08.07.2019    20:37           3021 scoop-alias.ps1
-a---          08.07.2019    20:37           1142 scoop-bucket.ps1
-a---          08.07.2019    20:37           1662 scoop-cache.ps1
-a---          24.10.2020    17:16           1809 scoop-checkup.ps1
-a---          08.07.2019    20:37           2494 scoop-cleanup.ps1
-a---          08.07.2019    20:37           1530 scoop-config.ps1
-a---          08.07.2019    20:37           1545 scoop-create.ps1
-a---          08.07.2019    20:37            723 scoop-depends.ps1
-a---          08.07.2019    20:37           1776 scoop-export.ps1
-a---          20.11.2021    00:53           1216 scoop-help.ps1
-a---          24.10.2020    17:16            772 scoop-hold.ps1
-a---          08.07.2019    20:37            612 scoop-home.ps1
-a---          01.11.2021    19:34           4301 scoop-info.ps1
-a---          18.10.2019    21:19           4436 scoop-install.ps1
-a---          24.10.2020    17:16           1812 scoop-list.ps1
-a---          08.07.2019    20:37            551 scoop-prefix.ps1
-a---          01.11.2021    19:34           2883 scoop-reset.ps1
-a---          08.07.2019    20:37           3712 scoop-search.ps1
-a---          08.07.2019    20:37           2879 scoop-status.ps1
-a---          24.10.2020    17:16            774 scoop-unhold.ps1
-a---          01.11.2021    19:43           4465 scoop-uninstall.ps1
-a---          03.11.2021    21:12          12879 scoop-update.ps1
-a---          03.11.2021    21:12           8794 scoop-virustotal.ps1
-a---          08.07.2019    20:37           1330 scoop-which.ps1
```

2. shims folder
```powershell
λ  ls .\shims\scoop-*

    Directory: C:\Users\<anton>\scoop\shims

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---          10.11.2020    21:20            290 scoop-bucket-origin.ps1
-a---          10.11.2020    21:20             70 scoop-cache-rm-all.ps1
-a---          10.11.2020    21:20             71 scoop-cache-show-all.ps1
-a---          10.11.2020    21:20             73 scoop-cleanup-all.ps1
-a---          10.11.2020    21:20            301 scoop-info-all.ps1
-a---          10.11.2020    21:20            167 scoop-list-all.ps1
-a---          10.11.2020    21:20            350 scoop-search-info.ps1
-a---          08.07.2019    20:37           7680 scoop-search.exe
-a---          22.01.2021    18:24            283 scoop-search.ps1
-a---          22.01.2021    18:24             77 scoop-search.shim
-a---          08.07.2021    21:44             70 scoop-update-all.ps1
```

If it helps, in my ```C:\Users\<user>\.config\scoop\config.json``` there is

```powershell
  "alias": {
    "update-all": "scoop-update-all",
    "cache-show-all": "scoop-cache-show-all",
    "cache-rm-all": "scoop-cache-rm-all",
    "cleanup-all": "scoop-cleanup-all",
    "list-all": "scoop-list-all",
    "info-all": "scoop-info-all",
    "search-info": "scoop-search-info",
    "bucket-origin": "scoop-bucket-origin"
  }
```

And many of those aliases are due to ```https://github.com/AntonOks/scoop-aoks/blob/master/bucket/alias-additions-aoks.json```

**Comment by AntonOks** [comment]
> I do not get this error when I type just `scoop` (in either Windows PowerShell or PowerShell Core).
> 
> I wonder what source you're using for the repo - since I can see some additional commands in your help section. Are those custom aliases?

Yeap. Aliases, initially found [here](https://github.com/snaphat/alias-additions.git) but now adopted a bit and now using ```https://github.com/AntonOks/scoop-aoks/blob/master/bucket/alias-additions-aoks.json```

**Comment by AntonOks** [comment]
Looking at my shims, I think I have an idea... as "my" problem seams to be related to "search"...

I always also do a ```scoop install https://raw.githubusercontent.com/tokiedokie/scoop-search/master/scoop-search.json```, which my somehow confuse scoops ```scoop search``` aka ```scoop-search.ps1```?!?

**Comment by pratikpc** [comment]
> Looking at my shims, I think I have an idea... as "my" problem seams to be related to "search"...

Yep!

This fix proposed isn't the best of ideas IMHO.

If there are clashes, they should be obvious to the users

**Comment by pratikpc** [comment]
@AntonOks maybe a fix which would make these issues a lot more clearer?

**Comment by AntonOks** [comment]
> > Looking at my shims, I think I have an idea... as "my" problem seams to be related to "search"...
> 
> Yep!
> 
> This fix proposed isn't the best of ideas IMHO.
> 
> If there are clashes, they should be obvious to the users

Well, now we have a discussion...

Your feedback is 100% valid, no doubts. Nevertheless, just to have the same understanding on the way forward...

1. If a user installs a command, which is considered a 100% drop-in replacement for any SCOOP internal command and therefore overlays the internal one, the seen error here should not pop-up anyhow and can just be omitted.
Agreed?
IF so, something like my "hack", which simply skips the given "ForEach-Object" if a key exists already, should be "ok", I guess.
And as I haven't seen any other problems with all my adoptions in the last years so far, it seam SCOOP has no other "problems" with overlaying commands...

If what you say, is: "Please add some more clarification to the output of SCOOP **_if it is run without any additional command line option_**" (!!!), I could do so... but I'm not sure this "info / warning / error" makes sense from the users perspective or would more confuse them?! 

2. The other and more general way could be to disallow additions of commands, which do overlay SCOOP standard / internal commands. This may break things today, but be a saver way forward?!

**Comment by AntonOks** [comment]
again, as I understand the seen problem... it's only happening if you run SCOOP without any additional sub-command.. which may be a "fallback" for "scoop help", I guess (?), so seen there as well.

and if you run SCOOP that way, it obviously should print the infos / help from WHAT will happen IF you later run SCOOP with the appropriate sub-command, right?
This than means my current fix is already solving the initial problem... because in our case here "scoop search" is always the internal command and if I want the overlaying additional one, I need to run it with its original "scoop-search(.exe)" name...

If we agree here, the hole discussion may be skipped for this pull request anyhow.... any maybe some of the SCOOP Devs want to take it and discuss how to tackle "overlay" (shadowing) commands in the future...

**Comment by rashil2000** [comment]
Superseded by #5002

**Pull request closed without merging**
