### PR TITLE
Merge branch 'develop' into master

### PR DESCRIPTION
**Pull request by niheaven**
- #3518 @rasa @niheaven 
  - #4502
- #4494 @pratikpc 
- #4422 @r0uv3n
- #3281 @niheaven 
- #4372 @worldyun Co-authored-by: @niheaven 
  - e35ff313a5d35cab1049024938c3423a5f6bf060 47ebc6f176b0db0afeb51b4ee237a20b2d8649e9
- #4504 @rasa 
- #4229 @zoritle
- #3721 @niheaven 
  - ae892138423bb9bbf54c8f0bed8331b93199f6b8 e663027299d03ca768a252fa4bcbc51d124d4cae
- #3292 @Retia-Adolf Co-authored-by: @niheaven 
- #3352 @niheaven 
- #3871 @filmor

### CODE REVIEW

**Review by pratikpc — APPROVED** [review]
Develop has been stable enough for me!!

**Comment by issaclin32** [comment]
I have been using the *develop* branch (`scoop config branch develop`), and hasn't encounter a problem so far.

**Comment by rashil2000** [comment]
Should we prepare some release notes type of thing? 

There have been many changes, it'll be good to document them.

**Comment by niheaven** [comment]
Emm, there isn't a NEWS.md in this repo, and neither a release circle...

I've added all the changes in PR's content and may add NEWS.md in master after this is merged, and maintained it in `develop`.

There is a discussion that Scoop Core may have stable release and since I'm not familiar with GitHub's release, may someone else help?

**Comment by rashil2000** [comment]
From the tags page (https://github.com/ScoopInstaller/Scoop/tags) I can see there were some releases in the past (albeit without any notes, just tags are there).

We can create a tag from master (after this PR is merged) and create a release from that tag, see:

image

**Comment by rasa** [comment]
Works for me! Thanks for all the great work!

**Comment by niheaven** [comment]
🎉 But, where's the ~~review approval~~? I cannot merge it without them 😭

**Review by rashil2000 — APPROVED** [review]

**Comment by pratikpc** [comment]
@niheaven need to rebase develop now

> This branch is 9 commits behind master.

**Comment by niheaven** [comment]
> @niheaven need to rebase develop now
> 
> > This branch is 9 commits behind master.

Done.

**Pull request merged**
