### PR TITLE
fix(decompress): Fix nested Zstd archive extraction

### PR DESCRIPTION
**Pull request by niheaven**
Also fix test cases error

#### Description

There're some stupid mistakes in `Expand-ZstdArchive()` which are totally introduced by me (#4372). This one fixes them, and bypasses decompress test.

#### How Has This Been Tested?

image

#### Checklist:

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
- [x] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

**Comment by rashil2000** [comment]
Do you have a manifest to test before and after this change?

**Comment by niheaven** [comment]
Run the test, since before and after the PR, msys type manifest always works well...

The error only occured when destination dir is not archive dir.

PS, test will hault before since waiting for interaction of overwriting, and a wrong function name...

**Comment by niheaven** [comment]
I made a test manifest:

<details>
<summary>test.json</summary>

```json
{
    "version": "11.2.0-2",
    "description": "GNU Compiler Collection (Mingw-w64 port from MSYS2 project)",
    "homepage": "http://mingw-w64.org/doku.php",
    "license": "GPL-3.0-or-later,ZPL-2.1,...",
    "architecture": {
        "64bit": {
            "url": [
                "https://mirror.msys2.org/mingw/mingw64/mingw-w64-x86_64-binutils-2.37-4-any.pkg.tar.zst"
            ],
            "hash": [
                "a518d2630c11fe363abd394763d0bb82fdde72386ffb58d87ecc8f46cbe878d6"
            ]
        },
        "32bit": {
            "url": [
                "https://mirror.msys2.org/mingw/mingw32/mingw-w64-i686-binutils-2.37-4-any.pkg.tar.zst"
            ],
            "hash": [
                "20b2e5beefb831c665ac5b1be4feb447e0f4e543e15c0fd5855dc0c258a29a02"
            ]
        }
    },
    "extract_to": "test"
}
```

</details>

Before:

image

After:

image

**Comment by niheaven** [comment]
@rashil2000 Do you have some time to test this PR (I've attached a testing manifest)? I've some `test` fixes that based on this...

**Review by rashil2000 — APPROVED** [review]

**Comment by chawyehsu** [comment]
Looks like the tests of `Expand-ZstdArchive` are false negative. They all fail on CI despite pass on local machine...

https://ci.appveyor.com/project/chawyehsu/scoop/build/job/g5alk2c1s63s50aj#L245

@niheaven Could you please take a look at this. I don't know why the Core's appveyor CI stopped.

**Comment by niheaven** [comment]
I'll check in my clone... The bucket error is located and will be fixed soon.

**Pull request merged**
