### PR TITLE
fix(psmodules): Remove folder recursively when unlinking previous module path

### PR DESCRIPTION
**Pull request by AkariiinMKII**
#### Description

Add a `-Recurse` parameter to `Remove-Item` cmdlet when unlinking psmodule path.
#### Motivation and Context

- Relates to #5126

#### How Has This Been Tested?

I've tested my codes by performing update for the same app, everything seems ok 

```powershell
Linking ~\scoop\modules\WhoAteMyRAM => ~\scoop\apps\WhoAteMyRAM\current
WARN  ~\scoop\modules\WhoAteMyRAM already exists. It will be replaced.
Running post_install script...
'WhoAteMyRAM' (1.0.10) was installed successfully!
```

Changes may effect:

https://github.com/ScoopInstaller/Scoop/blob/d63b7d6f01bb33c473172715d1007751baf937de/libexec/scoop-uninstall.ps1#L85

https://github.com/ScoopInstaller/Scoop/blob/4a31bd330244f7f89f16208cdddda3f9edac2d65/lib/install.ps1#L60

#### Checklist:

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
- [x] I have ensured that I am targeting the `develop` branch.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.
- [x] I have added an entry in the CHANGELOG.

### CODE REVIEW

**Comment by rashil2000** [comment]
Could this also solve #4844?

**Comment by AkariiinMKII** [comment]
> Could this also solve #4844?

Nope I guess, his issue happens in uninstallation progress, while mine happens in installation progress.

**Comment by rashil2000** [comment]
Which PS module do you face this error in? Does it happen in any/all PS modules?

**Comment by AkariiinMKII** [comment]
> Which PS module do you face this error in? Does it happen in any/all PS modules?

Yes, it happens in all modules.

**Comment by rashil2000** [comment]
I am unable to repro this issue:

image

**Comment by AkariiinMKII** [comment]
> I am unable to repro this issue:
> 
> image

Maybe it's because of PS version
image
image

**Comment by AkariiinMKII** [comment]
There is another solution that we run `uninstall_psmodule` during update process.

**Review by rashil2000 — DISMISSED** [review]
Right, the prompt appears in PS 5.1 

This should fix it.

**Review by niheaven — DISMISSED** [review]

**Pull request merged**
