### PR TITLE
fix(shim): Run JAR file from app's root directory

### PR DESCRIPTION
**Pull request by niheaven**
#### Description

For Java apps, the working directory should be apps' root directory since config files are normally located beside `.jar`.

#### Checklist:

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
- [x] I have ensured that I am targeting the `develop` branch.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.
- [x] I have added an entry in the CHANGELOG.

### CODE REVIEW

**Comment by niheaven** [comment]
I'm not sure if `.py` or other executives need such tweaks.

**Comment by rashil2000** [comment]
Why WSL check?

**Comment by niheaven** [comment]
WSL couldn't recognize `D:/aaa/bbb`-type path, since it uses `/mnt/D/aaa/bbb`, while Cygwin could access `D:/aaa/bbb` correctly.

**Comment by niheaven** [comment]
Some use cases: https://github.com/ScoopInstaller/Main/pull/5702, https://github.com/ScoopInstaller/Main/pull/5704

**Comment by rashil2000** [comment]
I recognize the usefulness of this feature, but still don't get the WSL part - do we really need to handle the use case where bash scripts (meant to run in Git Bash etc.) would be run inside WSL Bash? Wouldn't that lead to additional problems?

**Comment by niheaven** [comment]
WSL shares PATH with the host machine, so if you install Java and can run in pwsh, you can run it in WSL too. That's why we should consider such cases.

**Review by rashil2000 — APPROVED** [review]

**Pull request merged**
