### PR TITLE
refactor(path): Use 'Convert-Path()' instead of 'Resolve-Path()'

### PR DESCRIPTION
**Pull request by niheaven**
#### Description

Use `Convert-Path()` instead of `Resolve-Path()` while the latter will *resolve* the **wildcard** characters in a path (we just want to *convert* a path from a PowerShell path to a PowerShell provider path or *expand* a path)

#### Motivation and Context

None

#### How Has This Been Tested?

Internal tests passed, all functions should work well, and more tests should be made.

#### Checklist:

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
- [x] I have ensured that I am targeting the `develop` branch.
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.
- [x] I have added an entry in the CHANGELOG.

### CODE REVIEW

**Comment by niheaven** [comment]
Any comments here, guys?

**Comment by rashil2000** [comment]
Are there any bugs we're facing with Resolve-Path? I don't see a reason to change what's already working.

**Comment by niheaven** [comment]
As what I said, `Resolve-Path` is used to *RESOLVE* or *GUESS* the path, such as `Resolve-Path windows`, just see its examples [here](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/resolve-path?view=powershell-5.1#examples). What we used in Scoop is just `Convert-Path`, e.g. expand `.` or `~`.

And there is another benefit here, `Resolve-Path` outputs `[System.Management.Automation.PathInfo]` which may be handled incorrectly while `Convert-Path` outputs `[System.String]`.

**Review by rashil2000 — APPROVED** [review]

**Comment by Hrxn** [comment]
> As what I said, `Resolve-Path` is used to _RESOLVE_ or _GUESS_ the path, such as `Resolve-Path windows`, just see its examples [here](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/resolve-path?view=powershell-5.1#examples). What we used in Scoop is just `Convert-Path`, e.g. expand `.` or `~`.
> 

Not really. That example is specific to `$PWD  = C:\`
`Resolve-Path` does not "guess" any paths..

> And there is another benefit here, `Resolve-Path` outputs `[System.Management.Automation.PathInfo]` which may be handled incorrectly while `Convert-Path` outputs `[System.String]`.
> 

Yeah, that's the one important difference between these two cmdlets.
One could argue that using `PathInfo` objects would be beneficial over using just strings, but this depends on the use case.
If you're dealing with paths represented as strings anyway, then `Convert-Path` is just fine, yes..

The other important difference is that `Resolve-Path` does support using `PSCredential` for credentialed access, but this is probably not relevant for scoop's case..

**Pull request merged**
