### PR TITLE
fix(shim): Fix shim when app path has white spaces

### LINKED ISSUE #4728: [Bug] Shims fail if path contains spaces
## Bug Report

git

### Current Behaviour

Scoop is unable to run command: "Could not create process with command <...>"

### Expected Behaviour

Scoop should update

### Additional context/output

My username has a space in between. 

### Possible Solution

The git shim should be updated to: 
path = "C:\Users\User Name\scoop\apps\git\current\cmd\git.exe"

### System details

**Windows version:** 11

**OS architecture:** 64bit

**PowerShell version:**5.1.22000.282

#### Scoop Configuration

```json
{
    "lastupdate":  "2022-01-27T14:48:14.5181152+01:00",
    "SCOOP_REPO":  "https://github.com/lukesampson/scoop",
    "SCOOP_BRANCH":  "master"
}
```

### PR DESCRIPTION
**Pull request by niheaven**
#### Description

Enclose app path with double quotes to fix bug while app path has white spaces.

#### Motivation and Context

Closes #4728

#### How Has This Been Tested?

Only occurred in exe shims, hard to test.

#### Checklist:

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
- [x] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by rashil2000** [comment]
I think we should wait for more people to test this. I have used multiple custom shims with whitespaces, and they work.

**Comment by jbtls** [comment]
Hey @rashil2000 how can i test it?

**Comment by niheaven** [comment]
Using `gh` (`scoop install gh`), under you scoop root folder (xxx\apps\scoop\current) run `gh pr checkout 4734`), then install some apps to test the shim.

**Comment by rashil2000** [comment]
Simpler method would be:
```
scoop config SCOOP_BRANCH fix-shim
scoop update
```

**Comment by jbtls** [comment]
Tested it with some shims. Seems to work good.

**Comment by niheaven** [comment]
@rashil2000 Does this break something?

**Comment by rashil2000** [comment]
I don't think so, but I have been unable to reproduce the original issue for a long time. 

My $Env:SCOOP points to 'E:\Scoop Stuff' and all my shims work 😢

**Comment by niheaven** [comment]
Aha, I could not reproduce, too... Maybe some Env setting or OS version related?

If it is harmless for other code or users, merging this tends to be not a bad choice.

**Review by rashil2000 — APPROVED** [review]
Yeah, let's fix later if it break anything

**Pull request merged**
