### PR TITLE
fix(current): Remove 'current' while it's not a junction

### PR DESCRIPTION
**Pull request by niheaven**
#### Description

Junction is copied as native folder when we copy `apps` folder, and this may break scoop's `reset`, `uninstall`, `cleanup` actions. Use `Remove-Item -Recure` could fix this bug.

#### How Has This Been Tested?

```pwsh
❯ Copy-Item D:\Scoop\apps\ag D:\ -Recurse
❯ scoop uninstall ag
Uninstalling 'ag' (2.2.5).
Removing shim 'ag.exe'.
Removing shim 'ag.shim'.
Unlinking D:\Scoop\apps\ag\current
'ag' was uninstalled.
❯ Move-Item D:\ag D:\Scoop\apps
❯ scoop prefix ag
D:\Scoop\apps\ag\current
❯ (Get-Item D:\Scoop\apps\ag\current).GetType()

IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     False    DirectoryInfo                            System.IO.FileSystemInfo

❯ scoop reset ag
```

Before:

```pwsh
❯ (Get-Item D:\Scoop\apps\ag\current).LinkType -eq 'Junction'
False
```

After:

```pwsh
❯ (Get-Item D:\Scoop\apps\ag\current).LinkType -eq 'Junction'
True
```

#### Checklist:

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
- [x] I have updated the documentation accordingly.
- [ ] ~I have updated the tests accordingly.~

### CODE REVIEW

**Comment by rashil2000** [comment]
> BTW, use `New-Item -ItemType Junction` instead of `mklink /j` to make current junction.

Just to confirm, this works in PS 5.1 and Win 7/8 also, right?

There are 3 more places that use `mklink` (see https://cs.github.com/ScoopInstaller/Scoop?q=mklink) - 2 in lib/install.ps1 and 1 in lib/psmodule.ps1. We can replace those too.

**Comment by niheaven** [comment]
Okay, I'll revert the change here (mklink) and change them all in another PR to make clear change.

**Comment by rashil2000** [comment]
Some more places where we can use `Remove-Item` instead of `rmdir`. Would be cool to refactor them too.


https://github.com/ScoopInstaller/Scoop/blob/2644a5f7b1014a3b5843ecddbf8c739beb2ed802/lib/install.ps1#L1195

https://github.com/ScoopInstaller/Scoop/blob/2644a5f7b1014a3b5843ecddbf8c739beb2ed802/lib/install.ps1#L1198

https://github.com/ScoopInstaller/Scoop/blob/2644a5f7b1014a3b5843ecddbf8c739beb2ed802/lib/psmodules.ps1#L26

https://github.com/ScoopInstaller/Scoop/blob/2644a5f7b1014a3b5843ecddbf8c739beb2ed802/lib/psmodules.ps1#L43

**Comment by niheaven** [comment]
See https://github.com/ScoopInstaller/Scoop/pull/3502/files#diff-cfd4446b6fd477007943865889b4cdbf84e1c089d960b82cd3b57c6bf019fce3 for my previous rework of removing directory. I'm separating #3502 into single purpose PRs, and this should be next job soon.

**Comment by rashil2000** [comment]
Hmm. I just wanted to get rid of COMSPEC entirely, because I faced a ton of issues `The system cannot find the path specified.` today after migrating Scoop to a different drive. This was addressed earlier in https://github.com/ScoopInstaller/Scoop/pull/3993 but only in lib/git.ps1 file.

I'm under the impression that anything COMSPEC does can be handled by PS 5.1 or later.

**Comment by niheaven** [comment]
Yes, of course, everything `COMSPEC` (a.k.a. `cmd.exe`) does could be handled by PowerShell Cmdlets.

I'll do a PR and it should be tested to see if there are some disadvantages.

**Review by rashil2000 — APPROVED** [review]

**Pull request merged**
