### PR TITLE
fix(scoop-bucket): Fix date formatting issues with git bucket(s)

### PR DESCRIPTION
**Pull request by HUMORCE**
#### Motivation and Context
Relates to https://github.com/ScoopInstaller/Scoop/pull/4756

#### Checklist:

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
- [ ] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Review by rashil2000 — DISMISSED** [review]

**Comment by rashil2000** [comment]
One more thing. I don't think we need quotes for 
```
"`"$source`"" 
```
variable. Meaning we can just say 
```
$source
```

while calling git. Can you check once?

**Comment by HUMORCE** [comment]
you are right, the git command still works fine after removing them, but many code still uses quotes like this.

so, i will not change them in this PR.

**Comment by rashil2000** [comment]
I actually wanted to remind you in your original buckets PR, but I forgot 😅

The only places where double quotes are needed are those where we use `git_cmd` function, because that function is run by cmd.exe. For generic `git` calls, parameters are handled by PowerShell so quoting is not needed.

**Comment by HUMORCE** [comment]
okay, i did not notice that.

also removed them from L18 of `scoop-status.ps1`.

**Review by rashil2000 — DISMISSED** [review]

**Comment by niheaven** [comment]
Please update CHANGELOG, thanks

**Pull request merged**
