### PR TITLE
chore(release): Bump to version 0.2.4

### LINKED ISSUE #2121: Report the bucket name installing from
If you have a package that's available in two different buckets, scoop doesn't tell you which bucket it's installing an app from. For now, it should tell you the bucket's name, but eventually, perhaps it asks you which one you want?

### LINKED ISSUE #5038: [Feature] disable cache
#### Describe the solution you'd like
I would like the ability to disable cache. I just pruned the cache folder and regained 40GB. 
I just want to disable it. I don't installing, uninstalling and reinstalling, so im not saving any time.

### LINKED ISSUE #5044: [Bug] Optionally disable remote-checking in `scoop status`
#### Current Behavior
scoop status takes ~3 times more time in v0.2.3 vs v.0.2.2

#### Additional context/output
scoop status in v0.2.3
image

scoop status in v0.2.2
image

top functions
image

#### Possible Solution
It seems that in 0.2.3 Test-UpdateStatus is run for each bucket which is quite expensive.
image

### System details
windows 11 (21H2 build 22000.778)
x64
ps core: 7.2.5
git version 2.37.0.windows.1

#### Scoop Configuration

```json
{
  "lastupdate": "2022-07-12T16:41:04.1824139+02:00",
  "SCOOP_REPO": "https://github.com/lukesampson/scoop",
  "SCOOP_BRANCH": "master",
  "shim": "kiennq",
  "aria2-warning-enabled": false
}
```

### LINKED ISSUE #5046: [Feature] Status output: Improve the spacing/formatting for the text when an app has failed to install
image

Noticed that the text was very tight for an app that didn't successfully install.

#### Is your feature request related to a problem? Please describe.

Not really a problem, just a matter of spacing and UI design.

#### Describe the solution you'd like

It could be:

**"Installation failed - Manifest removed"**

Something simple like that would instantly improve the design.

#### Describe alternatives you've considered

While testing the behavior by resizing the terminal window to be smaller or bigger, I didn't really find any alternatives coming to mind.

### PR DESCRIPTION
**Pull request by niheaven**
### Features

- **core:** Create no window by default in `Invoke-ExternalCommand` (#5066)
- **core:** Improve argument concatenation in `Invoke-ExternalCommand` (#5065)
- **install:** Show bucket name while installing an app (#5075)
- **scoop-status:** Add flag to disable remote checking (#5073)
- **scoop-update:** Add support for `pre_uninstall` and `post_uninstall` (#5085)

### Bug Fixes

- **core:** Avoid deadlock in `Invoke-ExternalCommand` (#5064)
- **core:** Use 'System.Nullable<bool>' for param 'global' (#5088)
- **install:** Move from cache when `--no-cache` is specified (#5039)
- **scoop-status:** Correct formatting of `Info` output (#5047)

### Builds
- **checkver:** Load page content before running 'script' (#5080)
- **json:** Update Newtonsoft.Json.Schema to 3.0.15-beta2 (#5053)

## Close Issues

- Closes #5046
- Closes #5038
- Closes #5042
- Closes https://github.com/ScoopInstaller/Java/issues/409
- Closes #2121
- Closes #5044
- Closes https://github.com/ScoopInstaller/Java/issues/412

## Credits

Thanks to the following contributors (ordered by PR merging time):

@lewis-yeung @rashil2000 @niheaven @yi-Xu-0100

### CODE REVIEW

**Comment by niheaven** [comment]
Wait for #5073

**Review by rashil2000 — DISMISSED** [review]

**Comment by yi-Xu-0100** [comment]
@rashil2000 @niheaven Could you wait and review for #5085? It is a simple fix/feature, but useful for some apps which running behind the background that need pre_uninstall to kill the process. 😁

**Comment by niheaven** [comment]
> @rashil2000 @niheaven Could you wait and review for #5085? It is a simple fix/feature, but useful for some apps which running behind the background that need pre_uninstall to kill the process. 😁

Done.

**Review by rashil2000 — APPROVED** [review]

**Comment by niheaven** [comment]
Ping @chawyehsu @issaclin32

**Review by issaclin32 — APPROVED** [review]

**Pull request merged**
