### PR TITLE
chore(config): Document all configuration options

### PR DESCRIPTION
**Pull request by rashil2000**
#### Checklist:

- [x] I have updated the documentation accordingly.
- [ ] I have updated the tests accordingly.

### CODE REVIEW

**Comment by rashil2000** [comment]
Let me know if I missed any setting

**Review by issaclin32 — APPROVED** [review]

**Comment by niheaven** [comment]
```yml
force-update: Force apps updating to bucket's version
shim: Choose scoop shim builds
rootPath: Root path of scoop, default '$env:USERPROFILE\scoop'
globalPath: Global root path of scoop, default '$env:ProgramData\scoop'
cachePath: Cache path of scoop, default '$rootPath\cache'
```

**Comment by rashil2000** [comment]
Can we actually use variables in the config values? Will scoop do a string substitution on them?

**Comment by niheaven** [comment]
Environment Variables could be used, but other local variables should not.

**Comment by rashil2000** [comment]
Then `$rootPath\cache` shouldn't be used, right?

**Comment by niheaven** [comment]
Yes, it is the default value, but user cannot set as is.

**Comment by rashil2000** [comment]
Right. 
So if we show 

```
# cachePath: $rootPath\cache
```

in the help doc, users will think it's okay to use variables.

So we should either leave it empty (and write default value in description), or write an example valid path here.

**Comment by niheaven** [comment]
Use `'cache' folder under Scoop root directory`?

**Review by rasa — APPROVED** [review]

**Comment by rashil2000** [comment]
@niheaven done

**Comment by rashil2000** [comment]
Should we also document environment variables used by scoop? Like SCOOP_HOME and SCOOP_CHECKVER_TOKEN. Are there any more?

**Comment by niheaven** [comment]
In wiki or homepage, IMO.

`SCOOP`, `SCOOP_GLOBAL`, `SCOOP_CACHE`, read before `rootPath`, `globalPath`, `cahePath` config.

**Comment by rashil2000** [comment]
Updated the Readme 👍

**Review by niheaven — APPROVED** [review]

**Pull request merged**
