### PR TITLE
docs(changelog): Bump to v0.1.0

### PR DESCRIPTION
**Pull request by niheaven**
#### Description

Bump CHANGELOG to ~v0.9.0~ v0.1.0 and change tag's URL to tag comparison.

#### Checklist:

- [x] I have read the [Contributing Guide](https://github.com/ScoopInstaller/.github/blob/main/.github/CONTRIBUTING.md).
- [x] I have updated the documentation accordingly.
- [x] I have updated the tests accordingly.

### CODE REVIEW

**Comment by rashil2000** [comment]
I think this is going to be a massive release with tons of new features and fixes. Should we go with a more important version bump like 0.1.0.0  or 1.0.0.0?

**Comment by niheaven** [comment]
`0.1.0.0` is too small while `1.0.0.0` is too big 🤣  So I choose a near-finish version 0.9.0 (BTW, dev version needs not be added, IMO)

**Comment by niheaven** [comment]
Yes, but scoop is a near 10-year project, should `0.1.0` be a reasonable version?

@ScoopInstaller/maintainers What's your opinion?

**Comment by HUMORCE** [comment]
any version below `1.0.0` is acceptable to me.

**Review by rashil2000 — APPROVED** [review]

**Comment by niheaven** [comment]
Waiting sometimes to merge if @ScoopInstaller/maintainers have other opinions.

**Pull request merged**
